//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_HWI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNSD_5G_Dump
    {
        public System.DateTime timestamp { get; set; }
        public string NE_Name { get; set; }
        public string NR_DU_Cell_ID { get; set; }
        public string NR_DU_Cell_Name { get; set; }
        public string Duplex_Mode { get; set; }
        public string Cell_ID { get; set; }
        public string Physical_Cell_ID { get; set; }
        public string Frequency_Band { get; set; }
        public string Uplink_NARFCN { get; set; }
        public string Downlink_NARFCN { get; set; }
        public string Uplink_Bandwidth { get; set; }
        public string Downlink_Bandwidth { get; set; }
        public string Cell_Radius_m { get; set; }
        public string Subcarrier_Spacing_KHz { get; set; }
        public string Cyclic_Prefix_Length { get; set; }
        public string Slot_Assignment { get; set; }
        public string Slot_Structure { get; set; }
        public string RAN_Notification_Area_ID { get; set; }
        public string LampSite_Cell_Flag { get; set; }
        public string Tracking_Area_ID { get; set; }
        public string TA_Offset { get; set; }
        public string Cell_Administration_State { get; set; }
        public string SSB_Frequency_Position_Describe_Method { get; set; }
        public string SSB_Frequency_Position { get; set; }
        public string SSB_Period_ms { get; set; }
        public string SIB1_Period_ms { get; set; }
        public string Logical_Root_Sequence_Index { get; set; }
        public string PRACH_Frequency_Start_Position { get; set; }
        public string NR_DU_Cell_TRP_ID { get; set; }
        public string NR_DU_Cell_ID2 { get; set; }
        public string Transmit_and_Receive_Mode { get; set; }
        public string Baseband_Equipment_ID { get; set; }
        public string Max_Transmit_Power_0_1dBm { get; set; }
        public string CPRI_Compression { get; set; }
        public string Baseband_Resource_Mutual_Aid_Switch { get; set; }
        public string Branch_CPRI_Compression { get; set; }
        public string NR_DU_Cell_TRP_ID2 { get; set; }
        public string Coverage_Scenario { get; set; }
        public string Tilt_degree { get; set; }
        public string Azimuth_degree { get; set; }
        public string Max_SSB_Power_Offset_dB { get; set; }
        public string Scenario_Beam_Algorithm_Switch { get; set; }
        public string Cell_Activate_State { get; set; }
        public string Tracking_Area_Code { get; set; }
    }
}
