//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFWIMAXMOBCARRIER
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal CARRIERNO { get; set; }
        public decimal DCARRIERNO { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public decimal FREQUENCY { get; set; }
        public decimal DFREQUENCY { get; set; }
        public decimal BANDWIDTH { get; set; }
        public decimal DBANDWIDTH { get; set; }
        public Nullable<decimal> FRAMEDURATION { get; set; }
        public Nullable<decimal> DFRAMEDURATION { get; set; }
        public Nullable<decimal> TRANSITIONGAP { get; set; }
        public Nullable<decimal> DTRANSITIONGAP { get; set; }
        public Nullable<decimal> CYCLICPREFIX { get; set; }
        public Nullable<decimal> DCYCLICPREFIX { get; set; }
        public Nullable<decimal> DUPLEX { get; set; }
        public Nullable<decimal> DDUPLEX { get; set; }
        public Nullable<decimal> DLFUSC { get; set; }
        public Nullable<decimal> DDLFUSC { get; set; }
        public Nullable<decimal> DLPUSC { get; set; }
        public Nullable<decimal> DDLPUSC { get; set; }
        public Nullable<decimal> FIXMAPDL { get; set; }
        public Nullable<decimal> DFIXMAPDL { get; set; }
        public Nullable<decimal> FIXMAPUL { get; set; }
        public Nullable<decimal> DFIXMAPUL { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<decimal> DLAMC { get; set; }
        public Nullable<decimal> DDLAMC { get; set; }
        public Nullable<decimal> ULAMC { get; set; }
        public Nullable<decimal> DULAMC { get; set; }
        public Nullable<decimal> DLOPUSC { get; set; }
        public Nullable<decimal> DDLOPUSC { get; set; }
        public Nullable<decimal> ULOPUSC { get; set; }
        public Nullable<decimal> DULOPUSC { get; set; }
        public Nullable<decimal> ULPUSC { get; set; }
        public Nullable<decimal> DULPUSC { get; set; }
        public string IDNAME { get; set; }
        public string DIDNAME { get; set; }
    }
}
