//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFMASTHEADAMP
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal MHAKEY { get; set; }
        public decimal DMHAKEY { get; set; }
        public string IDNAME { get; set; }
        public string DIDNAME { get; set; }
        public Nullable<decimal> NOISEFIG { get; set; }
        public Nullable<decimal> DNOISEFIG { get; set; }
        public Nullable<decimal> MAXGAIN { get; set; }
        public Nullable<decimal> DMAXGAIN { get; set; }
        public Nullable<decimal> INSLOSS { get; set; }
        public Nullable<decimal> DINSLOSS { get; set; }
        public string DESCRIPTION { get; set; }
        public string DDESCRIPTION { get; set; }
        public string PHOTOFILE { get; set; }
        public string DPHOTOFILE { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> EQUIPICONKEY { get; set; }
        public Nullable<decimal> DEQUIPICONKEY { get; set; }
        public Nullable<decimal> SUPPLIERKEY { get; set; }
        public Nullable<decimal> DSUPPLIERKEY { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> DCOST { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> DWEIGHT { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
