//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFLINKENDFEED
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal LINKENDFEEDERSETTINGSKEY { get; set; }
        public decimal DLINKENDFEEDERSETTINGSKEY { get; set; }
        public decimal PTPLINKENDKEY { get; set; }
        public decimal DPTPLINKENDKEY { get; set; }
        public decimal LINKENDANTENNAKEY { get; set; }
        public decimal DLINKENDANTENNAKEY { get; set; }
        public Nullable<decimal> FEEDERKEY { get; set; }
        public Nullable<decimal> DFEEDERKEY { get; set; }
        public Nullable<decimal> FEEDERLENGTH { get; set; }
        public Nullable<decimal> DFEEDERLENGTH { get; set; }
        public Nullable<decimal> OVERRIDEFEEDERLOSS { get; set; }
        public Nullable<decimal> DOVERRIDEFEEDERLOSS { get; set; }
        public Nullable<decimal> USERFEEDERLOSS { get; set; }
        public Nullable<decimal> DUSERFEEDERLOSS { get; set; }
        public Nullable<decimal> RADIOFLAG { get; set; }
        public Nullable<decimal> DRADIOFLAG { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
