//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFPRLLINK
    {
        public decimal PRLPK { get; set; }
        public decimal DPRLPK { get; set; }
        public string IDNAME { get; set; }
        public string DIDNAME { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public Nullable<decimal> ISTEMPLATE { get; set; }
        public Nullable<decimal> DISTEMPLATE { get; set; }
        public Nullable<decimal> OBJECTTYPE { get; set; }
        public Nullable<decimal> DOBJECTTYPE { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<decimal> DVISIBILITY { get; set; }
        public Nullable<decimal> DVISIBILITYGROUP { get; set; }
        public Nullable<decimal> VISIBILITY { get; set; }
        public Nullable<decimal> VISIBILITYGROUP { get; set; }
    }
}
