//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFCARLAY
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal CARLAYKEY { get; set; }
        public decimal DCARLAYKEY { get; set; }
        public string IDNAME { get; set; }
        public string DIDNAME { get; set; }
        public string ABBREVIATION { get; set; }
        public string DABBREVIATION { get; set; }
        public Nullable<decimal> MAXCARRIERS { get; set; }
        public Nullable<decimal> DMAXCARRIERS { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> DTYPE { get; set; }
        public Nullable<decimal> USEREUSEPATTERN { get; set; }
        public Nullable<decimal> DUSEREUSEPATTERN { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> FREQBANDKEY { get; set; }
        public Nullable<decimal> DFREQBANDKEY { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
