//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFLOGWIMAXMOBCAR
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal CARRIERPK { get; set; }
        public decimal DCARRIERPK { get; set; }
        public decimal LOGNODEFK { get; set; }
        public decimal DLOGNODEFK { get; set; }
        public decimal WIMAXMOBCARRIERFK { get; set; }
        public decimal DWIMAXMOBCARRIERFK { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> SUBCHANDLPUSC { get; set; }
        public Nullable<decimal> DSUBCHANDLPUSC { get; set; }
        public Nullable<decimal> SUBCHANDLFUSC { get; set; }
        public Nullable<decimal> DSUBCHANDLFUSC { get; set; }
        public Nullable<decimal> SUBCHANULPUSC { get; set; }
        public Nullable<decimal> DSUBCHANULPUSC { get; set; }
        public Nullable<decimal> SUBCHANDLAMC { get; set; }
        public Nullable<decimal> DSUBCHANDLAMC { get; set; }
        public Nullable<decimal> SUBCHANULAMC { get; set; }
        public Nullable<decimal> DSUBCHANULAMC { get; set; }
        public Nullable<decimal> SUBCHANDLOPUSC { get; set; }
        public Nullable<decimal> DSUBCHANDLOPUSC { get; set; }
        public Nullable<decimal> SUBCHANULOPUSC { get; set; }
        public Nullable<decimal> DSUBCHANULOPUSC { get; set; }
        public Nullable<decimal> PREAMBLEFREQ { get; set; }
        public Nullable<decimal> DPREAMBLEFREQ { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public decimal DLOGNODETYPEFK { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
    }
}
