//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFLOGICALOP
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public string NODEID { get; set; }
        public string DNODEID { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal DFILTERKEY { get; set; }
        public decimal TYPE { get; set; }
        public decimal DTYPE { get; set; }
        public decimal TREELEVEL { get; set; }
        public decimal DTREELEVEL { get; set; }
        public decimal LOGICALOPKEY { get; set; }
        public decimal DLOGICALOPKEY { get; set; }
        public Nullable<decimal> PARENTLOGICALOPKEY { get; set; }
        public Nullable<decimal> DPARENTLOGICALOPKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<decimal> SORTORDER { get; set; }
        public Nullable<decimal> DSORTORDER { get; set; }
    }
}
