//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFFIVEGCELLCAR
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal CELLCARRIERPK { get; set; }
        public decimal DCELLCARRIERPK { get; set; }
        public decimal LOGCELLFK { get; set; }
        public decimal DLOGCELLFK { get; set; }
        public decimal CELLPARAMSFK { get; set; }
        public decimal DCELLPARAMSFK { get; set; }
        public decimal CARRIERFK { get; set; }
        public decimal DCARRIERFK { get; set; }
        public Nullable<decimal> MAXTXPOWER { get; set; }
        public Nullable<decimal> DMAXTXPOWER { get; set; }
        public decimal DLNOISERISETERMUMTS { get; set; }
        public decimal DDLNOISERISETERMUMTS { get; set; }
        public decimal DLNOISERISETERMGSM { get; set; }
        public decimal DDLNOISERISETERMGSM { get; set; }
        public decimal DLNOISERISETERMLTE { get; set; }
        public decimal DDLNOISERISETERMLTE { get; set; }
        public decimal DLNOISERISETERMWIFI { get; set; }
        public decimal DDLNOISERISETERMWIFI { get; set; }
        public decimal ULNOISERISECELLTERMUMTS { get; set; }
        public decimal DULNOISERISECELLTERMUMTS { get; set; }
        public decimal ULNOISERISECELLTERMGSM { get; set; }
        public decimal DULNOISERISECELLTERMGSM { get; set; }
        public decimal ULNOISERISECELLTERMLTE { get; set; }
        public decimal DULNOISERISECELLTERMLTE { get; set; }
        public decimal ULNOISERISECELLTERMWIFI { get; set; }
        public decimal DULNOISERISECELLTERMWIFI { get; set; }
        public decimal CHANNELPROTECTIONUMTS { get; set; }
        public decimal DCHANNELPROTECTIONUMTS { get; set; }
        public decimal CHANNELPROTECTIONGSM { get; set; }
        public decimal DCHANNELPROTECTIONGSM { get; set; }
        public decimal CHANNELPROTECTIONLTE { get; set; }
        public decimal DCHANNELPROTECTIONLTE { get; set; }
        public decimal CHANNELPROTECTIONWIFI { get; set; }
        public decimal DCHANNELPROTECTIONWIFI { get; set; }
        public Nullable<decimal> CODESCHEMAKEY { get; set; }
        public Nullable<decimal> DCODESCHEMAKEY { get; set; }
        public Nullable<decimal> CODESCHEMATYPE { get; set; }
        public Nullable<decimal> DCODESCHEMATYPE { get; set; }
        public decimal CELLID { get; set; }
        public decimal DCELLID { get; set; }
        public Nullable<decimal> SSSPBCH { get; set; }
        public Nullable<decimal> DSSSPBCH { get; set; }
        public Nullable<decimal> PSS { get; set; }
        public Nullable<decimal> DPSS { get; set; }
        public Nullable<decimal> PDCCH { get; set; }
        public Nullable<decimal> DPDCCH { get; set; }
        public Nullable<decimal> PDSCH { get; set; }
        public Nullable<decimal> DPDSCH { get; set; }
        public Nullable<decimal> CSIRS { get; set; }
        public Nullable<decimal> DCSIRS { get; set; }
        public Nullable<decimal> NOISEFIGURE { get; set; }
        public Nullable<decimal> DNOISEFIGURE { get; set; }
        public Nullable<byte> CELLCAENABLED { get; set; }
        public Nullable<byte> DCELLCAENABLED { get; set; }
        public string CACELLIDENTITY { get; set; }
        public string DCACELLIDENTITY { get; set; }
        public Nullable<byte> REFSIGNALSNRTHRESHENABLED { get; set; }
        public Nullable<byte> DREFSIGNALSNRTHRESHENABLED { get; set; }
        public Nullable<decimal> REFSIGNALSNRTHRESH { get; set; }
        public Nullable<decimal> DREFSIGNALSNRTHRESH { get; set; }
        public Nullable<byte> TIMINGADVANCEENABLED { get; set; }
        public Nullable<byte> DTIMINGADVANCEENABLED { get; set; }
        public Nullable<decimal> TIMINGADVANCEMODE { get; set; }
        public Nullable<decimal> DTIMINGADVANCEMODE { get; set; }
        public Nullable<decimal> MAXTA { get; set; }
        public Nullable<decimal> DMAXTA { get; set; }
        public Nullable<decimal> MAXRANGE { get; set; }
        public Nullable<decimal> DMAXRANGE { get; set; }
        public Nullable<byte> ADMIMOTHRESHENABLED { get; set; }
        public Nullable<byte> DADMIMOTHRESHENABLED { get; set; }
        public Nullable<decimal> ADMIMOTHRESHULTRAFFICSINR { get; set; }
        public Nullable<decimal> DADMIMOTHRESHULTRAFFICSINR { get; set; }
        public Nullable<decimal> ADMIMOTHRESHDLTRAFFICSINR { get; set; }
        public Nullable<decimal> DADMIMOTHRESHDLTRAFFICSINR { get; set; }
        public Nullable<byte> MUMIMOTHRESHENABLED { get; set; }
        public Nullable<byte> DMUMIMOTHRESHENABLED { get; set; }
        public Nullable<decimal> MUMIMOTHRESHULTRAFFICSINR { get; set; }
        public Nullable<decimal> DMUMIMOTHRESHULTRAFFICSINR { get; set; }
        public Nullable<decimal> MUMIMOTHRESHDLTRAFFICSINR { get; set; }
        public Nullable<decimal> DMUMIMOTHRESHDLTRAFFICSINR { get; set; }
        public Nullable<byte> BFTHRESHENABLED { get; set; }
        public Nullable<byte> DBFTHRESHENABLED { get; set; }
        public Nullable<decimal> BFTHRESHULTRAFFICSINR { get; set; }
        public Nullable<decimal> DBFTHRESHULTRAFFICSINR { get; set; }
        public Nullable<decimal> BFTHRESHDLTRAFFICSINR { get; set; }
        public Nullable<decimal> DBFTHRESHDLTRAFFICSINR { get; set; }
        public Nullable<byte> RSRPOFFSETENABLED { get; set; }
        public Nullable<byte> DRSRPOFFSETENABLED { get; set; }
        public Nullable<decimal> RSRPOFFSET { get; set; }
        public Nullable<decimal> DRSRPOFFSET { get; set; }
        public Nullable<decimal> SCHEDULERKEY { get; set; }
        public Nullable<decimal> DSCHEDULERKEY { get; set; }
        public Nullable<decimal> MAXSCHEDULEDUSERS { get; set; }
        public Nullable<decimal> DMAXSCHEDULEDUSERS { get; set; }
        public Nullable<decimal> MAXDLMODULATION { get; set; }
        public Nullable<decimal> DMAXDLMODULATION { get; set; }
        public Nullable<byte> LINEOFSIGHTLOCATIONENABLED { get; set; }
        public Nullable<byte> DLINEOFSIGHTLOCATIONENABLED { get; set; }
        public Nullable<byte> HIGHSINRLOCATIONENABLED { get; set; }
        public Nullable<byte> DHIGHSINRLOCATIONENABLED { get; set; }
        public Nullable<decimal> SINRTHRESHOLD { get; set; }
        public Nullable<decimal> DSINRTHRESHOLD { get; set; }
        public Nullable<decimal> NONRAYLEIGHADJUSTMENT { get; set; }
        public Nullable<decimal> DNONRAYLEIGHADJUSTMENT { get; set; }
        public Nullable<decimal> DLLOADPERCENTAGE { get; set; }
        public Nullable<decimal> DDLLOADPERCENTAGE { get; set; }
        public Nullable<decimal> ULNOISERISE { get; set; }
        public Nullable<decimal> DULNOISERISE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<byte> ASSIGNED_FIRST_RSI { get; set; }
        public Nullable<byte> ASSIGNED_NUM_RSI { get; set; }
        public Nullable<byte> DASSIGNED_FIRST_RSI { get; set; }
        public Nullable<byte> DASSIGNED_NUM_RSI { get; set; }
        public Nullable<decimal> DDELAY_SPREAD { get; set; }
        public Nullable<decimal> DELAY_SPREAD { get; set; }
        public Nullable<short> DPRACH_CONFIG_INDEX { get; set; }
        public Nullable<short> DPRACH_FDM { get; set; }
        public Nullable<short> DPRACH_FREQ_START { get; set; }
        public Nullable<byte> DPRACH_NCS { get; set; }
        public Nullable<byte> DPRACH_RESTRICTEDSET { get; set; }
        public Nullable<decimal> DPRACH_SUBCARRIER_SPACING { get; set; }
        public Nullable<byte> DPRACH_ZCZC { get; set; }
        public Nullable<byte> DPREAMBLE_FORMAT { get; set; }
        public Nullable<bool> DRSI_CALC_METHOD { get; set; }
        public Nullable<decimal> DRSI_SCHEMA_FK { get; set; }
        public Nullable<short> PRACH_CONFIG_INDEX { get; set; }
        public Nullable<short> PRACH_FDM { get; set; }
        public Nullable<short> PRACH_FREQ_START { get; set; }
        public Nullable<byte> PRACH_NCS { get; set; }
        public Nullable<byte> PRACH_RESTRICTEDSET { get; set; }
        public Nullable<decimal> PRACH_SUBCARRIER_SPACING { get; set; }
        public Nullable<byte> PRACH_ZCZC { get; set; }
        public Nullable<byte> PREAMBLE_FORMAT { get; set; }
        public Nullable<bool> RSI_CALC_METHOD { get; set; }
        public Nullable<decimal> RSI_SCHEMA_FK { get; set; }
        public Nullable<byte> DDSSDL { get; set; }
        public string DDSSID { get; set; }
        public Nullable<decimal> DDSSPRACHRBS { get; set; }
        public Nullable<byte> DDSSUL { get; set; }
        public Nullable<byte> DSSDL { get; set; }
        public string DSSID { get; set; }
        public Nullable<decimal> DSSPRACHRBS { get; set; }
        public Nullable<byte> DSSUL { get; set; }
    }
}
