//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFRADIOAMCTHRESHOLD
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal RADIOEQUIPPK { get; set; }
        public decimal DRADIOEQUIPPK { get; set; }
        public decimal MODTYPEKEY { get; set; }
        public decimal DMODTYPEKEY { get; set; }
        public Nullable<decimal> MINTXPOWER { get; set; }
        public Nullable<decimal> DMINTXPOWER { get; set; }
        public Nullable<decimal> MAXTXPOWER { get; set; }
        public Nullable<decimal> DMAXTXPOWER { get; set; }
        public Nullable<decimal> RXPOWER { get; set; }
        public Nullable<decimal> DRXPOWER { get; set; }
        public Nullable<decimal> MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<decimal> AD { get; set; }
        public Nullable<decimal> ATPCRANGE { get; set; }
        public Nullable<decimal> BM { get; set; }
        public Nullable<decimal> BNM { get; set; }
        public Nullable<decimal> DAD { get; set; }
        public Nullable<decimal> DATPCRANGE { get; set; }
        public Nullable<decimal> DBM { get; set; }
        public Nullable<decimal> DBNM { get; set; }
        public Nullable<decimal> DKN { get; set; }
        public Nullable<decimal> DMAXIPCAPACITY { get; set; }
        public Nullable<decimal> DMSM { get; set; }
        public Nullable<decimal> DNOCHANNELS { get; set; }
        public Nullable<decimal> DREDUCEDRATIO { get; set; }
        public Nullable<decimal> DTAUM { get; set; }
        public Nullable<decimal> DTAUNM { get; set; }
        public Nullable<decimal> DTHRESHOLD1 { get; set; }
        public Nullable<decimal> DTHRESHOLD2 { get; set; }
        public Nullable<decimal> DTIOBJECTIVE { get; set; }
        public Nullable<decimal> DWM { get; set; }
        public Nullable<decimal> DWNM { get; set; }
        public Nullable<decimal> DXPIFRANGE { get; set; }
        public Nullable<decimal> KN { get; set; }
        public Nullable<decimal> MAXIPCAPACITY { get; set; }
        public Nullable<decimal> MSM { get; set; }
        public Nullable<decimal> NOCHANNELS { get; set; }
        public Nullable<decimal> REDUCEDRATIO { get; set; }
        public Nullable<decimal> TAUM { get; set; }
        public Nullable<decimal> TAUNM { get; set; }
        public Nullable<decimal> THRESHOLD1 { get; set; }
        public Nullable<decimal> THRESHOLD2 { get; set; }
        public Nullable<decimal> TIOBJECTIVE { get; set; }
        public Nullable<decimal> WM { get; set; }
        public Nullable<decimal> WNM { get; set; }
        public Nullable<decimal> XPIFRANGE { get; set; }
    }
}
