//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFHDRDLKPARAM
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal HDRDLKPARAMSPK { get; set; }
        public decimal DHDRDLKPARAMSPK { get; set; }
        public string IDNAME { get; set; }
        public string DIDNAME { get; set; }
        public Nullable<decimal> EBNO { get; set; }
        public Nullable<decimal> DEBNO { get; set; }
        public Nullable<decimal> BITRATE { get; set; }
        public Nullable<decimal> DBITRATE { get; set; }
        public Nullable<decimal> SLOTS { get; set; }
        public Nullable<decimal> DSLOTS { get; set; }
        public Nullable<decimal> BITS { get; set; }
        public Nullable<decimal> DBITS { get; set; }
        public Nullable<decimal> OHEADBITS { get; set; }
        public Nullable<decimal> DOHEADBITS { get; set; }
        public Nullable<decimal> TRAFFCHIPS { get; set; }
        public Nullable<decimal> DTRAFFCHIPS { get; set; }
        public Nullable<decimal> PER0 { get; set; }
        public Nullable<decimal> DPER0 { get; set; }
        public Nullable<decimal> PER1 { get; set; }
        public Nullable<decimal> DPER1 { get; set; }
        public Nullable<decimal> PER2 { get; set; }
        public Nullable<decimal> DPER2 { get; set; }
        public Nullable<decimal> PER3 { get; set; }
        public Nullable<decimal> DPER3 { get; set; }
        public Nullable<decimal> PER4 { get; set; }
        public Nullable<decimal> DPER4 { get; set; }
        public Nullable<decimal> EBNT0 { get; set; }
        public Nullable<decimal> DEBNT0 { get; set; }
        public Nullable<decimal> EBNT1 { get; set; }
        public Nullable<decimal> DEBNT1 { get; set; }
        public Nullable<decimal> EBNT2 { get; set; }
        public Nullable<decimal> DEBNT2 { get; set; }
        public Nullable<decimal> EBNT3 { get; set; }
        public Nullable<decimal> DEBNT3 { get; set; }
        public Nullable<decimal> EBNT4 { get; set; }
        public Nullable<decimal> DEBNT4 { get; set; }
        public Nullable<decimal> SPARE0 { get; set; }
        public Nullable<decimal> DSPARE0 { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> DSPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<decimal> DSPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
        public Nullable<decimal> DSPARE3 { get; set; }
        public Nullable<decimal> SPARE4 { get; set; }
        public Nullable<decimal> DSPARE4 { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
