//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFANTCONFGROUP
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal GROUPPK { get; set; }
        public decimal DGROUPPK { get; set; }
        public decimal DEVICEFK { get; set; }
        public decimal DDEVICEFK { get; set; }
        public string GROUPNAME { get; set; }
        public string DGROUPNAME { get; set; }
        public decimal NUMSSB { get; set; }
        public decimal DNUMSSB { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
