//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFPRLREF
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal PRLPK { get; set; }
        public decimal DPRLPK { get; set; }
        public decimal LINKPK { get; set; }
        public decimal DLINKPK { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public decimal OBJECTTYPE { get; set; }
        public decimal DOBJECTTYPE { get; set; }
        public Nullable<decimal> LEGNO { get; set; }
        public Nullable<decimal> DLEGNO { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
