//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFTGINDOORCLUTTERLOSS
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal SCHEMAKEY { get; set; }
        public decimal DSCHEMAKEY { get; set; }
        public decimal LOSSKEY { get; set; }
        public decimal DLOSSKEY { get; set; }
        public string CLUTTERNAME { get; set; }
        public string DCLUTTERNAME { get; set; }
        public Nullable<decimal> INDLOSS { get; set; }
        public Nullable<decimal> DINDLOSS { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
