//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFMUNODE
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal LOGNODEPK { get; set; }
        public decimal DLOGNODEPK { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
        public decimal DLOGNODETYPEFK { get; set; }
        public decimal SUPPORTEDTECHNOLOGY { get; set; }
        public decimal DSUPPORTEDTECHNOLOGY { get; set; }
        public decimal SUPPORTEDTECHNOLOGYDATA { get; set; }
        public decimal DSUPPORTEDTECHNOLOGYDATA { get; set; }
        public Nullable<decimal> NODEID { get; set; }
        public Nullable<decimal> DNODEID { get; set; }
        public Nullable<decimal> AGGREGATECAPACITY { get; set; }
        public Nullable<decimal> DAGGREGATECAPACITY { get; set; }
        public Nullable<decimal> HEXRADIUS { get; set; }
        public Nullable<decimal> DHEXRADIUS { get; set; }
        public Nullable<decimal> MINSECTORS { get; set; }
        public Nullable<decimal> DMINSECTORS { get; set; }
        public Nullable<decimal> MAXSECTORS { get; set; }
        public Nullable<decimal> DMAXSECTORS { get; set; }
        public Nullable<decimal> GRDCSTRNTFLAGS { get; set; }
        public Nullable<decimal> DGRDCSTRNTFLAGS { get; set; }
        public Nullable<decimal> NETWORKLEVEL { get; set; }
        public Nullable<decimal> DNETWORKLEVEL { get; set; }
        public Nullable<decimal> CABINKEY { get; set; }
        public Nullable<decimal> DCABINKEY { get; set; }
        public Nullable<decimal> BTSKEY { get; set; }
        public Nullable<decimal> DBTSKEY { get; set; }
        public Nullable<decimal> TOWERKEY { get; set; }
        public Nullable<decimal> DTOWERKEY { get; set; }
        public Nullable<decimal> BTSFIXED { get; set; }
        public Nullable<decimal> DBTSFIXED { get; set; }
        public Nullable<decimal> NODEBTYPEFK { get; set; }
        public Nullable<decimal> DNODEBTYPEFK { get; set; }
        public Nullable<decimal> RES1ULTOT { get; set; }
        public Nullable<decimal> DRES1ULTOT { get; set; }
        public Nullable<decimal> RES1DLTOT { get; set; }
        public Nullable<decimal> DRES1DLTOT { get; set; }
        public Nullable<decimal> RES1ULPRI { get; set; }
        public Nullable<decimal> DRES1ULPRI { get; set; }
        public Nullable<decimal> RES1DLPRI { get; set; }
        public Nullable<decimal> DRES1DLPRI { get; set; }
        public Nullable<decimal> RES1ULHO { get; set; }
        public Nullable<decimal> DRES1ULHO { get; set; }
        public Nullable<decimal> RES1DLHO { get; set; }
        public Nullable<decimal> DRES1DLHO { get; set; }
        public Nullable<decimal> RES2ULTOT { get; set; }
        public Nullable<decimal> DRES2ULTOT { get; set; }
        public Nullable<decimal> RES2DLTOT { get; set; }
        public Nullable<decimal> DRES2DLTOT { get; set; }
        public Nullable<decimal> RES2ULPRI { get; set; }
        public Nullable<decimal> DRES2ULPRI { get; set; }
        public Nullable<decimal> RES2DLPRI { get; set; }
        public Nullable<decimal> DRES2DLPRI { get; set; }
        public Nullable<decimal> RES2ULHO { get; set; }
        public Nullable<decimal> DRES2ULHO { get; set; }
        public Nullable<decimal> RES2DLHO { get; set; }
        public Nullable<decimal> DRES2DLHO { get; set; }
        public Nullable<decimal> RES3ULTOT { get; set; }
        public Nullable<decimal> DRES3ULTOT { get; set; }
        public Nullable<decimal> RES3DLTOT { get; set; }
        public Nullable<decimal> DRES3DLTOT { get; set; }
        public Nullable<decimal> RES3ULPRI { get; set; }
        public Nullable<decimal> DRES3ULPRI { get; set; }
        public Nullable<decimal> RES3DLPRI { get; set; }
        public Nullable<decimal> DRES3DLPRI { get; set; }
        public Nullable<decimal> RES3ULHO { get; set; }
        public Nullable<decimal> DRES3ULHO { get; set; }
        public Nullable<decimal> RES3DLHO { get; set; }
        public Nullable<decimal> DRES3DLHO { get; set; }
        public Nullable<decimal> NUMCHANSPOOL { get; set; }
        public Nullable<decimal> DNUMCHANSPOOL { get; set; }
        public Nullable<decimal> NFVELEMENT { get; set; }
        public Nullable<decimal> DNFVELEMENT { get; set; }
        public string NFVHOSTID { get; set; }
        public string DNFVHOSTID { get; set; }
        public Nullable<decimal> MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<decimal> DELTEFLAG { get; set; }
        public Nullable<decimal> DGNODEBID { get; set; }
        public Nullable<decimal> DLTEENODEBID { get; set; }
        public Nullable<decimal> ELTEFLAG { get; set; }
        public Nullable<decimal> GNODEBID { get; set; }
        public Nullable<decimal> LTEENODEBID { get; set; }
        public string DC_IDENTITY { get; set; }
        public Nullable<decimal> DC_SUPPORT_EN { get; set; }
        public Nullable<decimal> DC_SUPPORT_INTER { get; set; }
        public Nullable<decimal> DC_SUPPORT_LTE { get; set; }
        public Nullable<decimal> DC_SUPPORT_NE { get; set; }
        public Nullable<decimal> DC_SUPPORT_NR { get; set; }
        public string DDC_IDENTITY { get; set; }
        public Nullable<decimal> DDC_SUPPORT_EN { get; set; }
        public Nullable<decimal> DDC_SUPPORT_INTER { get; set; }
        public Nullable<decimal> DDC_SUPPORT_LTE { get; set; }
        public Nullable<decimal> DDC_SUPPORT_NE { get; set; }
        public Nullable<decimal> DDC_SUPPORT_NR { get; set; }
    
        public virtual DIFFLOGNODE DIFFLOGNODE { get; set; }
    }
}
