//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFANTGROUPIND
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal GPINDEXPK { get; set; }
        public decimal DGPINDEXPK { get; set; }
        public decimal CONFGRPFK { get; set; }
        public decimal DCONFGRPFK { get; set; }
        public decimal DEVICEFK { get; set; }
        public decimal DDEVICEFK { get; set; }
        public decimal BEAMINDEX { get; set; }
        public decimal DBEAMINDEX { get; set; }
        public decimal SSBINDEX { get; set; }
        public decimal DSSBINDEX { get; set; }
        public decimal CTRLBEAM { get; set; }
        public decimal DCTRLBEAM { get; set; }
        public decimal TRAFBEAM { get; set; }
        public decimal DTRAFBEAM { get; set; }
        public decimal CTRLINDEX { get; set; }
        public decimal DCTRLINDEX { get; set; }
        public decimal TRAFINDEX { get; set; }
        public decimal DTRAFINDEX { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
