//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFMWANTENNATYPE
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal MWANTENNAKEY { get; set; }
        public decimal DMWANTENNAKEY { get; set; }
        public string IDNAME { get; set; }
        public string DIDNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string DDESCRIPTION { get; set; }
        public string PHOTOFILE { get; set; }
        public string DPHOTOFILE { get; set; }
        public Nullable<decimal> GAIN { get; set; }
        public Nullable<decimal> DGAIN { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
        public Nullable<decimal> DFREQUENCY { get; set; }
        public Nullable<decimal> FRONTTOBACKRATIO { get; set; }
        public Nullable<decimal> DFRONTTOBACKRATIO { get; set; }
        public Nullable<decimal> MINOPFREQ { get; set; }
        public Nullable<decimal> DMINOPFREQ { get; set; }
        public Nullable<decimal> MAXOPFREQ { get; set; }
        public Nullable<decimal> DMAXOPFREQ { get; set; }
        public Nullable<decimal> DIAMETER { get; set; }
        public Nullable<decimal> DDIAMETER { get; set; }
        public Nullable<decimal> GAINTYPE { get; set; }
        public Nullable<decimal> DGAINTYPE { get; set; }
        public Nullable<decimal> TILTTYPE { get; set; }
        public Nullable<decimal> DTILTTYPE { get; set; }
        public Nullable<decimal> POLARISATION { get; set; }
        public Nullable<decimal> DPOLARISATION { get; set; }
        public string MANUFACTURER { get; set; }
        public string DMANUFACTURER { get; set; }
        public Nullable<decimal> EQUIPICONKEY { get; set; }
        public Nullable<decimal> DEQUIPICONKEY { get; set; }
        public Nullable<decimal> SUPPLIERKEY { get; set; }
        public Nullable<decimal> DSUPPLIERKEY { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> DCOST { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> DWEIGHT { get; set; }
        public Nullable<decimal> PARENTKEY { get; set; }
        public Nullable<decimal> DPARENTKEY { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public string MASK { get; set; }
        public string DMASK { get; set; }
        public Nullable<decimal> MASKSTYLE { get; set; }
        public Nullable<decimal> DMASKSTYLE { get; set; }
        public string FCCID { get; set; }
        public string DFCCID { get; set; }
        public string PATTERNID { get; set; }
        public string DPATTERNID { get; set; }
        public Nullable<decimal> HALFPOWERBEAMWIDTH { get; set; }
        public Nullable<decimal> DHALFPOWERBEAMWIDTH { get; set; }
    }
}
