//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFTERMMOBSPEED
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal TERMTYPEKEY { get; set; }
        public decimal DTERMTYPEKEY { get; set; }
        public string CODE { get; set; }
        public string DCODE { get; set; }
        public decimal PERCENTIN { get; set; }
        public decimal DPERCENTIN { get; set; }
        public decimal MINSPEED { get; set; }
        public decimal DMINSPEED { get; set; }
        public decimal MAXSPEED { get; set; }
        public decimal DMAXSPEED { get; set; }
        public decimal STDSPEED { get; set; }
        public decimal DSTDSPEED { get; set; }
        public decimal AVGSPEED { get; set; }
        public decimal DAVGSPEED { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
