//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFTGCARRIERADJ
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal TGCARRIERFK { get; set; }
        public decimal DTGCARRIERFK { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public Nullable<decimal> ULATT { get; set; }
        public Nullable<decimal> DULATT { get; set; }
        public Nullable<decimal> DLATT { get; set; }
        public Nullable<decimal> DDLATT { get; set; }
        public Nullable<decimal> CARRIER { get; set; }
        public Nullable<decimal> DCARRIER { get; set; }
        public decimal ROWINDEX { get; set; }
        public Nullable<decimal> DROWINDEX { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
