//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFFIVEGFREQBAND
    {
        public decimal FREQBANDPK { get; set; }
        public decimal DFREQBANDPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public string FREQBANDNAME { get; set; }
        public string DFREQBANDNAME { get; set; }
        public decimal DUPLEXMODE { get; set; }
        public decimal DDUPLEXMODE { get; set; }
        public Nullable<decimal> NRBAND { get; set; }
        public Nullable<decimal> DNRBAND { get; set; }
        public decimal ALLOWRASTEROFFSET { get; set; }
        public decimal DALLOWRASTEROFFSET { get; set; }
        public decimal FRMODE { get; set; }
        public decimal DFRMODE { get; set; }
        public Nullable<decimal> DLNRARFCNRASTERKHZ { get; set; }
        public Nullable<decimal> DDLNRARFCNRASTERKHZ { get; set; }
        public Nullable<decimal> DLCHANRASTERKHZ { get; set; }
        public Nullable<decimal> DDLCHANRASTERKHZ { get; set; }
        public decimal DLNRARFCNLO { get; set; }
        public decimal DDLNRARFCNLO { get; set; }
        public decimal DLNRARFCNHI { get; set; }
        public decimal DDLNRARFCNHI { get; set; }
        public Nullable<decimal> DLFREQLOMHZ { get; set; }
        public Nullable<decimal> DDLFREQLOMHZ { get; set; }
        public Nullable<decimal> DLFREQHIMHZ { get; set; }
        public Nullable<decimal> DDLFREQHIMHZ { get; set; }
        public Nullable<decimal> ULNRARFCNRASTERKHZ { get; set; }
        public Nullable<decimal> DULNRARFCNRASTERKHZ { get; set; }
        public Nullable<decimal> ULCHANRASTERKHZ { get; set; }
        public Nullable<decimal> DULCHANRASTERKHZ { get; set; }
        public decimal ULNRARFCNLO { get; set; }
        public decimal DULNRARFCNLO { get; set; }
        public decimal ULNRARFCNHI { get; set; }
        public decimal DULNRARFCNHI { get; set; }
        public Nullable<decimal> ULFREQLOMHZ { get; set; }
        public Nullable<decimal> DULFREQLOMHZ { get; set; }
        public Nullable<decimal> ULFREQHIMHZ { get; set; }
        public Nullable<decimal> DULFREQHIMHZ { get; set; }
        public Nullable<decimal> IS_LICENSED { get; set; }
        public Nullable<decimal> DIS_LICENSED { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<decimal> MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
