//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFCARRIEDTRAFFICDETAIL
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal CARTRAFDETPK { get; set; }
        public decimal DCARTRAFDETPK { get; set; }
        public decimal SERVICEKEYFK { get; set; }
        public decimal DSERVICEKEYFK { get; set; }
        public decimal TERMTYPEKEYFK { get; set; }
        public decimal DTERMTYPEKEYFK { get; set; }
        public decimal PARENTFK { get; set; }
        public decimal DPARENTFK { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<bool> PROTECTED { get; set; }
        public Nullable<bool> DPROTECTED { get; set; }
        public Nullable<decimal> THROUGHPUTDL { get; set; }
        public Nullable<decimal> DTHROUGHPUTDL { get; set; }
        public Nullable<decimal> INTRAHOTHROUGHPUTDL { get; set; }
        public Nullable<decimal> DINTRAHOTHROUGHPUTDL { get; set; }
        public Nullable<decimal> INTERHOTHROUGHPUTDL { get; set; }
        public Nullable<decimal> DINTERHOTHROUGHPUTDL { get; set; }
        public Nullable<decimal> THROUGHPUTUL { get; set; }
        public Nullable<decimal> DTHROUGHPUTUL { get; set; }
        public Nullable<decimal> INTRAHOTHROUGHPUTUL { get; set; }
        public Nullable<decimal> DINTRAHOTHROUGHPUTUL { get; set; }
        public Nullable<decimal> INTERHOTHROUGHPUTUL { get; set; }
        public Nullable<decimal> DINTERHOTHROUGHPUTUL { get; set; }
        public Nullable<decimal> TERMINALCOUNT { get; set; }
        public Nullable<decimal> DTERMINALCOUNT { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public decimal DTECHNOLOGY { get; set; }
        public decimal TECHNOLOGY { get; set; }
    }
}
