//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFACTIVEELEMENT
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal DFILTERKEY { get; set; }
        public decimal RULEKEY { get; set; }
        public decimal DRULEKEY { get; set; }
        public decimal ELEMENTTYPEKEY { get; set; }
        public decimal DELEMENTTYPEKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<decimal> DTECHNOLOGY { get; set; }
        public Nullable<decimal> TECHNOLOGY { get; set; }
        public Nullable<decimal> DTECHMODE { get; set; }
        public Nullable<decimal> TECHMODE { get; set; }
    }
}
