//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTERNALHTTPDATA
    {
        public decimal DATAPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal OBJECTTYPEFK { get; set; }
        public string ID { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> POSITION { get; set; }
        public Nullable<decimal> REQUESTTYPE { get; set; }
        public string CONTEXTINFO { get; set; }
    }
}
