//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILTER()
        {
            this.ACTIVEATTRIBs = new HashSet<ACTIVEATTRIB>();
            this.ACTIVEELEMENTS = new HashSet<ACTIVEELEMENT>();
            this.ACTIVEFLAGS = new HashSet<ACTIVEFLAG>();
            this.ACTIVEOBJECTS = new HashSet<ACTIVEOBJECT>();
            this.ACTIVEPOLYGONS = new HashSet<ACTIVEPOLYGON>();
            this.ACTIVEWFS = new HashSet<ACTIVEWF>();
            this.LOGICALOPS = new HashSet<LOGICALOP>();
            this.RULES = new HashSet<RULE>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal TYPE { get; set; }
        public string FILTERID { get; set; }
        public decimal PERMISSION { get; set; }
        public decimal CREATEUSER { get; set; }
        public decimal USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<decimal> PARENTKEY { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> LASTUSEDDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEATTRIB> ACTIVEATTRIBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEELEMENT> ACTIVEELEMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEFLAG> ACTIVEFLAGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEOBJECT> ACTIVEOBJECTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEPOLYGON> ACTIVEPOLYGONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEWF> ACTIVEWFS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGICALOP> LOGICALOPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RULE> RULES { get; set; }
    }
}
