//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRAPH
    {
        public decimal PROJECTNO { get; set; }
        public decimal GRAPHLISTTYPE { get; set; }
        public decimal GRAPHKEY { get; set; }
        public decimal ABSCISSA { get; set; }
        public decimal ORDINATE { get; set; }
        public decimal MODIFYUSER { get; set; }
    }
}
