//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRIDCONFIGCELL
    {
        public decimal PROJECTNO { get; set; }
        public decimal CONFIGCELLPK { get; set; }
        public decimal CONFIGFK { get; set; }
        public decimal OBJECTFK { get; set; }
        public decimal CELLFK { get; set; }
        public decimal OBJECTTYPEFK { get; set; }
        public decimal MODIFYUSER { get; set; }
    
        public virtual GRIDCONFIG GRIDCONFIG { get; set; }
    }
}
