//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGCELLFEEDER
    {
        public decimal CELLFEEDPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal LOGANTENNAFK { get; set; }
        public decimal ADDRESSFK { get; set; }
        public decimal LOGCELLFK { get; set; }
        public decimal FEEDERFK { get; set; }
        public Nullable<decimal> FEEDERLEN { get; set; }
        public decimal MHAFK { get; set; }
        public Nullable<decimal> MHAGAIN { get; set; }
        public decimal GSMACTIVE { get; set; }
        public decimal GSM1CELLLAYERFK { get; set; }
        public decimal GSM1PRIMODELFK { get; set; }
        public decimal GSM1SECMODELFK { get; set; }
        public decimal GSM2CELLLAYERFK { get; set; }
        public decimal GSM2PRIMODELFK { get; set; }
        public decimal GSM2SECMODELFK { get; set; }
        public decimal GSM3CELLLAYERFK { get; set; }
        public decimal GSM3PRIMODELFK { get; set; }
        public decimal GSM3SECMODELFK { get; set; }
        public decimal GSM4CELLLAYERFK { get; set; }
        public decimal GSM4PRIMODELFK { get; set; }
        public decimal GSM4SECMODELFK { get; set; }
        public decimal GSM5CELLLAYERFK { get; set; }
        public decimal GSM5PRIMODELFK { get; set; }
        public decimal GSM5SECMODELFK { get; set; }
        public Nullable<decimal> UMTSACTIVE { get; set; }
        public Nullable<decimal> UMTSULGAIN { get; set; }
        public Nullable<decimal> UMTSDLGAIN { get; set; }
        public Nullable<decimal> UMTSNOISE { get; set; }
        public Nullable<decimal> UMTSOTHERLOSSES { get; set; }
        public Nullable<decimal> UMTSDLMIMOSUPPORT { get; set; }
        public Nullable<decimal> UMTSDLMIMOMODE { get; set; }
        public Nullable<decimal> UMTSMIMORXELEM { get; set; }
        public Nullable<decimal> UMTSMIMOTXELEM { get; set; }
        public Nullable<decimal> UMTSTXDIVERSITY { get; set; }
        public Nullable<decimal> UMTSRXDIVERSITY { get; set; }
        public Nullable<decimal> LTEACTIVE { get; set; }
        public Nullable<decimal> LTEULGAIN { get; set; }
        public Nullable<decimal> LTEDLGAIN { get; set; }
        public Nullable<decimal> LTENOISE { get; set; }
        public Nullable<decimal> LTEOTHERLOSSES { get; set; }
        public Nullable<decimal> WIMAXACTIVE { get; set; }
        public Nullable<decimal> WIMAXTXDIVERSITY { get; set; }
        public Nullable<decimal> WIMAXRXDIVERSITY { get; set; }
        public Nullable<decimal> MOBWIMAXACTIVE { get; set; }
        public Nullable<decimal> MOBWIMAXULGAIN { get; set; }
        public Nullable<decimal> MOBWIMAXDLGAIN { get; set; }
        public Nullable<decimal> MOBWIMAXNOISE { get; set; }
        public Nullable<decimal> MOBWIMAXOTHERLOSSES { get; set; }
        public Nullable<decimal> MOBWIMAXDLMIMOSUPPORT { get; set; }
        public Nullable<decimal> MOBWIMAXDLMIMOMODE { get; set; }
        public Nullable<decimal> MOBWIMAXMIMORXELEM { get; set; }
        public Nullable<decimal> MOBWIMAXMIMOTXELEM { get; set; }
        public Nullable<decimal> MOBWIMAXULCOLLABMPLX { get; set; }
        public Nullable<decimal> MOBWIMAXAASSUPPORT { get; set; }
        public Nullable<decimal> MOBWIMAXNOAASELEM { get; set; }
        public Nullable<decimal> MOBWIMAXULINTF { get; set; }
        public Nullable<decimal> MOBWIMAXDLINTF { get; set; }
        public Nullable<decimal> MOBWIMAXULDIVSUPPORT { get; set; }
        public Nullable<decimal> CDMAACTIVE { get; set; }
        public Nullable<decimal> CDMATXDIVERSITY { get; set; }
        public Nullable<decimal> CDMARXDIVERSITY { get; set; }
        public Nullable<decimal> CDMAULGAIN { get; set; }
        public Nullable<decimal> CDMADLGAIN { get; set; }
        public Nullable<decimal> CDMANOISE { get; set; }
        public Nullable<decimal> CDMAOTHERLOSSES { get; set; }
        public Nullable<decimal> WIFIACTIVE { get; set; }
        public Nullable<decimal> FIVEGACTIVE { get; set; }
        public decimal MODIFYUSER { get; set; }
    
        public virtual LOGCELL LOGCELL { get; set; }
        public virtual LOGICALANTENNA LOGICALANTENNA { get; set; }
        public virtual SITEADDRESS SITEADDRESS { get; set; }
    }
}
