//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGCONNRTHOP
    {
        public decimal ROUTEHOPPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal LOGCONNRTFK { get; set; }
        public decimal LOGCONNFK { get; set; }
        public decimal LINKFK { get; set; }
        public Nullable<decimal> INDEXNO { get; set; }
        public Nullable<decimal> STARTEND { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
    
        public virtual LOGCONNROUTE LOGCONNROUTE { get; set; }
    }
}
