//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGICALOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGICALOP()
        {
            this.RULES = new HashSet<RULE>();
        }
    
        public decimal PROJECTNO { get; set; }
        public string NODEID { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal TYPE { get; set; }
        public decimal TREELEVEL { get; set; }
        public decimal LOGICALOPKEY { get; set; }
        public Nullable<decimal> PARENTLOGICALOPKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> SORTORDER { get; set; }
    
        public virtual FILTER FILTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RULE> RULES { get; set; }
    }
}
