//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIS95SECTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGIS95SECTOR()
        {
            this.LOGIS95SECCAR = new HashSet<LOGIS95SECCAR>();
        }
    
        public decimal LOGCELLFK { get; set; }
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> PNCODE { get; set; }
        public Nullable<decimal> NUMCHANSPOOL { get; set; }
        public Nullable<decimal> MAXHOCHANSPOOL { get; set; }
        public Nullable<decimal> MAXPRIMCHANSPOOL { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> SIGNALLINGOVERHEAD { get; set; }
        public Nullable<decimal> NBRLIMITINTERLTE { get; set; }
        public Nullable<decimal> ACTIVATION { get; set; }
        public Nullable<decimal> CELLOVERRIDECOLORREF { get; set; }
        public decimal CELLPARAMSPK { get; set; }
        public decimal CSAREA { get; set; }
        public decimal CSRANGE { get; set; }
        public decimal INDOORSCHEMAFK { get; set; }
        public string SECNAME { get; set; }
        public Nullable<decimal> NBRLIMITINTERFIVEG { get; set; }
    
        public virtual LOGCELL LOGCELL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIS95SECCAR> LOGIS95SECCAR { get; set; }
        public virtual TGCLUTTERLOSSSCHEMA TGCLUTTERLOSSSCHEMA { get; set; }
    }
}
