//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGICALANTENNA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGICALANTENNA()
        {
            this.GENREPEATERFEEDERs = new HashSet<GENREPEATERFEEDER>();
            this.LOGCELLFEEDERs = new HashSet<LOGCELLFEEDER>();
        }
    
        public decimal LOGANTENNAPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal ADDRESSFK { get; set; }
        public decimal PHYANTENNAFK { get; set; }
        public Nullable<decimal> INDEXNO { get; set; }
        public decimal ANTTYPEFK { get; set; }
        public string INSTANCEID { get; set; }
        public string PORTS { get; set; }
        public string DIPLEXERS { get; set; }
        public Nullable<decimal> INHERITMASTERPATTERN { get; set; }
        public Nullable<decimal> CORRFACTOR { get; set; }
        public Nullable<decimal> ULCORRFACTOR { get; set; }
        public Nullable<decimal> ISREPEATER { get; set; }
        public Nullable<decimal> ANTTYPEFIXED { get; set; }
        public Nullable<decimal> MINELECTILT { get; set; }
        public Nullable<decimal> MINELECTILTFIXED { get; set; }
        public Nullable<decimal> MAXELECTILT { get; set; }
        public Nullable<decimal> MAXELECTILTFIXED { get; set; }
        public Nullable<decimal> ELECTILTSTEP { get; set; }
        public Nullable<decimal> ELECTILTSTEPFIXED { get; set; }
        public Nullable<decimal> MINLOBETILT { get; set; }
        public Nullable<decimal> MINLOBETILTFIXED { get; set; }
        public Nullable<decimal> MAXLOBETILT { get; set; }
        public Nullable<decimal> MAXLOBETILTFIXED { get; set; }
        public Nullable<decimal> PREDMODELKEY1 { get; set; }
        public Nullable<decimal> PREDRADIUSMET1 { get; set; }
        public Nullable<decimal> PREDRESOLUTIONMET1 { get; set; }
        public Nullable<decimal> PREDMODELKEY2 { get; set; }
        public Nullable<decimal> PREDRADIUSMET2 { get; set; }
        public Nullable<decimal> PREDRESOLUTIONMET2 { get; set; }
        public Nullable<decimal> LEGACYNODEKEY { get; set; }
        public Nullable<decimal> LEGACYNODETYPEFK { get; set; }
        public Nullable<decimal> LEGACYNODEINDEX { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PATFREQUENCY { get; set; }
        public Nullable<decimal> SYNCRETGROUPINDEX { get; set; }
        public Nullable<decimal> ANTGROUPFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENREPEATERFEEDER> GENREPEATERFEEDERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGCELLFEEDER> LOGCELLFEEDERs { get; set; }
        public virtual SITEADDRESS SITEADDRESS { get; set; }
        public virtual PHYANTENNA PHYANTENNA { get; set; }
    }
}
