//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGUMTSCAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGUMTSCAR()
        {
            this.LOGUMTSCELLCARs = new HashSet<LOGUMTSCELLCAR>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal UMTSCARPK { get; set; }
        public Nullable<decimal> LOGNODEFK { get; set; }
        public Nullable<decimal> TGCARRIERFK { get; set; }
        public Nullable<decimal> MODIFYUSER { get; set; }
        public Nullable<decimal> RES1ULTOT { get; set; }
        public Nullable<decimal> RES1DLTOT { get; set; }
        public Nullable<decimal> RES1ULPRI { get; set; }
        public Nullable<decimal> RES1DLPRI { get; set; }
        public Nullable<decimal> RES1ULHO { get; set; }
        public Nullable<decimal> RES1DLHO { get; set; }
        public Nullable<decimal> RES2ULTOT { get; set; }
        public Nullable<decimal> RES2DLTOT { get; set; }
        public Nullable<decimal> RES2ULPRI { get; set; }
        public Nullable<decimal> RES2DLPRI { get; set; }
        public Nullable<decimal> RES2ULHO { get; set; }
        public Nullable<decimal> RES2DLHO { get; set; }
        public Nullable<decimal> RES3ULTOT { get; set; }
        public Nullable<decimal> RES3DLTOT { get; set; }
        public Nullable<decimal> RES3ULPRI { get; set; }
        public Nullable<decimal> RES3DLPRI { get; set; }
        public Nullable<decimal> RES3ULHO { get; set; }
        public Nullable<decimal> RES3DLHO { get; set; }
        public Nullable<decimal> LOGNODETYPEFK { get; set; }
    
        public virtual MUNODE MUNODE { get; set; }
        public virtual TGCARRIER TGCARRIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGUMTSCELLCAR> LOGUMTSCELLCARs { get; set; }
    }
}
