//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGWIMAXMOBCELLCAR
    {
        public decimal PROJECTNO { get; set; }
        public decimal CELLCARRIERPK { get; set; }
        public decimal LOGCELLFK { get; set; }
        public decimal CARRIERFK { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> CELLBGRNDNOISE { get; set; }
        public Nullable<decimal> ULNOISERISE { get; set; }
        public Nullable<decimal> MAXTXPOWER { get; set; }
        public Nullable<byte> TXPOWFIXED { get; set; }
        public Nullable<decimal> PILOTPOWER { get; set; }
        public Nullable<byte> PILOTPOWFIXED { get; set; }
        public decimal MODULATION { get; set; }
        public decimal DLTRAFFLOAD { get; set; }
        public Nullable<decimal> CODESCHEMAKEY { get; set; }
        public Nullable<decimal> CODESCHEMATYPE { get; set; }
        public decimal WIMAXPNINDEX { get; set; }
        public decimal WIMAXMOBCARRIERFREQ { get; set; }
        public decimal WIMAXMOBPUSCSECTORS { get; set; }
        public Nullable<decimal> PREAMBLEBOOSTING { get; set; }
        public Nullable<decimal> PILOTBOOSTING { get; set; }
        public Nullable<decimal> RXMOBSENS { get; set; }
        public decimal CELLPARAMSFK { get; set; }
    
        public virtual LOGCELL LOGCELL { get; set; }
        public virtual LOGWIMAXMOBCAR LOGWIMAXMOBCAR { get; set; }
        public virtual LOGWIMAXMOBCELL LOGWIMAXMOBCELL { get; set; }
    }
}
