//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGWIMAXMOBCAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGWIMAXMOBCAR()
        {
            this.LOGWIMAXMOBCELLCARs = new HashSet<LOGWIMAXMOBCELLCAR>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal CARRIERPK { get; set; }
        public decimal LOGNODEFK { get; set; }
        public decimal WIMAXMOBCARRIERFK { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> SUBCHANDLPUSC { get; set; }
        public Nullable<decimal> SUBCHANDLFUSC { get; set; }
        public Nullable<decimal> SUBCHANULPUSC { get; set; }
        public Nullable<decimal> SUBCHANDLAMC { get; set; }
        public Nullable<decimal> SUBCHANULAMC { get; set; }
        public Nullable<decimal> SUBCHANDLOPUSC { get; set; }
        public Nullable<decimal> SUBCHANULOPUSC { get; set; }
        public Nullable<decimal> PREAMBLEFREQ { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
    
        public virtual WIMAXMOBCARRIER WIMAXMOBCARRIER { get; set; }
        public virtual MUNODE MUNODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGWIMAXMOBCELLCAR> LOGWIMAXMOBCELLCARs { get; set; }
    }
}
