//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTIPATHCHANNELMODEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MULTIPATHCHANNELMODEL()
        {
            this.LOGLTECELLCARs = new HashSet<LOGLTECELLCAR>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal MPCMODELPK { get; set; }
        public string IDNAME { get; set; }
        public decimal EXCESSTAPDELAY1 { get; set; }
        public decimal RELATIVEPOWER1 { get; set; }
        public decimal EXCESSTAPDELAY2 { get; set; }
        public decimal RELATIVEPOWER2 { get; set; }
        public decimal EXCESSTAPDELAY3 { get; set; }
        public decimal RELATIVEPOWER3 { get; set; }
        public decimal EXCESSTAPDELAY4 { get; set; }
        public decimal RELATIVEPOWER4 { get; set; }
        public decimal EXCESSTAPDELAY5 { get; set; }
        public decimal RELATIVEPOWER5 { get; set; }
        public decimal EXCESSTAPDELAY6 { get; set; }
        public decimal RELATIVEPOWER6 { get; set; }
        public decimal EXCESSTAPDELAY7 { get; set; }
        public decimal RELATIVEPOWER7 { get; set; }
        public decimal EXCESSTAPDELAY8 { get; set; }
        public decimal RELATIVEPOWER8 { get; set; }
        public decimal EXCESSTAPDELAY9 { get; set; }
        public decimal RELATIVEPOWER9 { get; set; }
        public decimal EXCESSTAPDELAY10 { get; set; }
        public decimal RELATIVEPOWER10 { get; set; }
        public decimal EXCESSTAPDELAY11 { get; set; }
        public decimal RELATIVEPOWER11 { get; set; }
        public decimal EXCESSTAPDELAY12 { get; set; }
        public decimal RELATIVEPOWER12 { get; set; }
        public decimal EXCESSTAPDELAY13 { get; set; }
        public decimal RELATIVEPOWER13 { get; set; }
        public decimal EXCESSTAPDELAY14 { get; set; }
        public decimal RELATIVEPOWER14 { get; set; }
        public decimal EXCESSTAPDELAY15 { get; set; }
        public decimal RELATIVEPOWER15 { get; set; }
        public decimal EXCESSTAPDELAY16 { get; set; }
        public decimal RELATIVEPOWER16 { get; set; }
        public decimal EXCESSTAPDELAY17 { get; set; }
        public decimal RELATIVEPOWER17 { get; set; }
        public decimal EXCESSTAPDELAY18 { get; set; }
        public decimal RELATIVEPOWER18 { get; set; }
        public decimal EXCESSTAPDELAY19 { get; set; }
        public decimal RELATIVEPOWER19 { get; set; }
        public decimal EXCESSTAPDELAY20 { get; set; }
        public decimal RELATIVEPOWER20 { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGLTECELLCAR> LOGLTECELLCARs { get; set; }
    }
}
