//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONENUMBER
    {
        public decimal PROJECTNO { get; set; }
        public decimal PHONEKEY { get; set; }
        public Nullable<decimal> PERSONKEY { get; set; }
        public string PHONENUMBER1 { get; set; }
    
        public virtual CONTACTPERSON CONTACTPERSON { get; set; }
    }
}
