//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIORUSERLICCONFIG
    {
        public decimal USRKEYPK { get; set; }
        public decimal GRPKEYPK { get; set; }
        public string NAME { get; set; }
        public string VERSION { get; set; }
        public decimal ACTIVE { get; set; }
        public decimal ALLOWED { get; set; }
        public decimal COMMUTEALLOWED { get; set; }
    
        public virtual PRIORGROUP PRIORGROUP { get; set; }
        public virtual PRIORUSER PRIORUSER { get; set; }
    }
}
