//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RULE()
        {
            this.ACTIVEATTRIBs = new HashSet<ACTIVEATTRIB>();
            this.ACTIVEELEMENTS = new HashSet<ACTIVEELEMENT>();
            this.ACTIVEFLAGS = new HashSet<ACTIVEFLAG>();
            this.ACTIVEPOLYGONS = new HashSet<ACTIVEPOLYGON>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal RNOT { get; set; }
        public decimal RULEKEY { get; set; }
        public decimal RULETYPEKEY { get; set; }
        public decimal ATTRIBUTETYPEKEY { get; set; }
        public decimal LOGICALOPKEY { get; set; }
        public Nullable<decimal> ELEMENTTYPEKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEATTRIB> ACTIVEATTRIBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEELEMENT> ACTIVEELEMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEFLAG> ACTIVEFLAGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEPOLYGON> ACTIVEPOLYGONS { get; set; }
        public virtual ACTIVEWF ACTIVEWF { get; set; }
        public virtual FILTER FILTER { get; set; }
        public virtual LOGICALOP LOGICALOP { get; set; }
    }
}
