//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICECARRIER
    {
        public decimal SERVICECARRIERPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal SERVICEFK { get; set; }
        public decimal CARRIERFK { get; set; }
        public decimal CARRIERTYPE { get; set; }
        public decimal PRIORITY { get; set; }
        public decimal MODIFYUSER { get; set; }
    
        public virtual LOGNODETYPE LOGNODETYPE { get; set; }
        public virtual TGSERVICE TGSERVICE { get; set; }
    }
}
