//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITEADDRESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SITEADDRESS()
        {
            this.GENREPEATERFEEDERs = new HashSet<GENREPEATERFEEDER>();
            this.GRIDCANDIDATES = new HashSet<GRIDCANDIDATE>();
            this.LOGCELLs = new HashSet<LOGCELL>();
            this.LOGCELLFEEDERs = new HashSet<LOGCELLFEEDER>();
            this.LOGICALANTENNAs = new HashSet<LOGICALANTENNA>();
            this.LOGNODEs = new HashSet<LOGNODE>();
            this.PHYANTENNAs = new HashSet<PHYANTENNA>();
            this.PHYANTENNAPORTs = new HashSet<PHYANTENNAPORT>();
            this.PMPHUBs = new HashSet<PMPHUB>();
            this.PTPLINKENDs = new HashSet<PTPLINKEND>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal ADDRESSKEY { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string TOWN { get; set; }
        public string PROVINCE { get; set; }
        public string STATE { get; set; }
        public string POSTCODE { get; set; }
        public Nullable<decimal> PERSONKEY { get; set; }
        public string IDNAME { get; set; }
        public Nullable<decimal> DIRECTKEY { get; set; }
        public Nullable<decimal> GNDHEIGHT { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> SRCHRAD { get; set; }
        public Nullable<decimal> SRCHOVERRIDEVIEW { get; set; }
        public Nullable<decimal> NOMINALID { get; set; }
        public Nullable<decimal> TARGETSTATUS { get; set; }
        public string PROPERTYCODE { get; set; }
        public Nullable<decimal> LOCKSEARCHAREA { get; set; }
        public string FLAGVALUE { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> MASTSPACE { get; set; }
        public Nullable<decimal> MTTR { get; set; }
        public Nullable<decimal> BUILDINGHEIGHT { get; set; }
        public string PANFILE { get; set; }
        public Nullable<decimal> ASSOCMAST { get; set; }
        public Nullable<decimal> MOUNTING { get; set; }
        public Nullable<decimal> MAXHEIGHT { get; set; }
        public Nullable<decimal> MINHEIGHT { get; set; }
        public string MASTEXCLUDED { get; set; }
        public Nullable<decimal> ANTHEIGHTRULE { get; set; }
        public Nullable<decimal> ANTSTEPSIZE { get; set; }
        public string ANTHEIGHTLIST { get; set; }
        public Nullable<decimal> ANTCOLOCATION { get; set; }
        public Nullable<decimal> MINAZIMDIFF { get; set; }
        public Nullable<decimal> ANTSAMECELL { get; set; }
        public Nullable<decimal> OPTIMISATIONSTATUS { get; set; }
        public Nullable<decimal> GRIDCONSTRFLAGS { get; set; }
        public string PRECANDIDATENAME { get; set; }
        public Nullable<decimal> VISIBILITY { get; set; }
        public Nullable<decimal> VISIBILITYGROUP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENREPEATERFEEDER> GENREPEATERFEEDERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRIDCANDIDATE> GRIDCANDIDATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGCELL> LOGCELLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGCELLFEEDER> LOGCELLFEEDERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGICALANTENNA> LOGICALANTENNAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGNODE> LOGNODEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHYANTENNA> PHYANTENNAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHYANTENNAPORT> PHYANTENNAPORTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMPHUB> PMPHUBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PTPLINKEND> PTPLINKENDs { get; set; }
    }
}
