//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPLITTER
    {
        public decimal PROJECTNO { get; set; }
        public decimal SPLITTERKEY { get; set; }
        public string IDNAME { get; set; }
        public string MANUFACTURER { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> LOSS { get; set; }
        public string DESCRIPTION { get; set; }
        public string PHOTOFILE { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
    }
}
