//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERMTYCARRIER
    {
        public decimal TERMTYCARRIERPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal TERMTYPEFK { get; set; }
        public decimal CARRIERFK { get; set; }
        public decimal CARRIERTYPE { get; set; }
        public Nullable<decimal> PCELLSUPPORTED { get; set; }
        public Nullable<decimal> SCELLSUPPORTED { get; set; }
        public decimal MODIFYUSER { get; set; }
    
        public virtual LOGNODETYPE LOGNODETYPE { get; set; }
        public virtual TERMTYPE TERMTYPE { get; set; }
    }
}
