//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGSERVBIT
    {
        public decimal PROJECTNO { get; set; }
        public decimal SERVICEKEY { get; set; }
        public decimal BITRATEKEY { get; set; }
        public decimal CARRIER { get; set; }
        public decimal PRIORITY { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public decimal PWRACT { get; set; }
        public decimal TPTACT { get; set; }
        public decimal RESACT { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public decimal MODIFYUSER { get; set; }
    }
}
