//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMESLOTMAP
    {
        public decimal PROJECTNO { get; set; }
        public decimal TIMESLOTMAPKEY { get; set; }
        public string NAME { get; set; }
        public decimal INTERCONKEY { get; set; }
        public string TS0 { get; set; }
        public string TS1 { get; set; }
        public string TS2 { get; set; }
        public string TS3 { get; set; }
        public string TS4 { get; set; }
        public string TS5 { get; set; }
        public string TS6 { get; set; }
        public string TS7 { get; set; }
        public string TS8 { get; set; }
        public string TS9 { get; set; }
        public string TS10 { get; set; }
        public string TS11 { get; set; }
        public string TS12 { get; set; }
        public string TS13 { get; set; }
        public string TS14 { get; set; }
        public string TS15 { get; set; }
        public string TS16 { get; set; }
        public string TS17 { get; set; }
        public string TS18 { get; set; }
        public string TS19 { get; set; }
        public string TS20 { get; set; }
        public string TS21 { get; set; }
        public string TS22 { get; set; }
        public string TS23 { get; set; }
        public string TS24 { get; set; }
        public string TS25 { get; set; }
        public string TS26 { get; set; }
        public string TS27 { get; set; }
        public string TS28 { get; set; }
        public string TS29 { get; set; }
        public string TS30 { get; set; }
        public string TS31 { get; set; }
        public string COMMENTS { get; set; }
        public string ENDAEQUIP { get; set; }
        public string ENDBEQUIP { get; set; }
    }
}
