//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERLINKTEMPRANGE
    {
        public decimal RANGEKEY { get; set; }
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> RANGEFROM { get; set; }
        public Nullable<decimal> RANGETO { get; set; }
        public Nullable<byte> RANGELINKTYPE { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> MODIFYUSER { get; set; }
    }
}
