//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Asset10
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSSERVICE
    {
        public decimal PROJECTNO { get; set; }
        public decimal WFSSERVICEPK { get; set; }
        public string IDNAME { get; set; }
        public string ENDPOINTADDR { get; set; }
        public decimal WFSVERSION { get; set; }
        public decimal REQTIMEOUT { get; set; }
        public string METADATA { get; set; }
        public decimal CREATEUSER { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal USERGROUP { get; set; }
        public decimal PERMISSION { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public System.DateTime MODIFYDATE { get; set; }
        public decimal QRYLIFETIME { get; set; }
        public string EPSGCODE { get; set; }
    }
}
