//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVEFLAGS
    {
        public decimal PROJECTNO { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal RULEKEY { get; set; }
        public decimal FLAGKEY { get; set; }
        public decimal FLAGGROUPKEY { get; set; }
        public Nullable<decimal> NUMBER1 { get; set; }
        public Nullable<decimal> NUMBER2 { get; set; }
        public string STRING { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> TECHNOLOGY { get; set; }
    
        public virtual FLAGGROUPS FLAGGROUPS { get; set; }
        public virtual FILTERS FILTERS { get; set; }
        public virtual RULES RULES { get; set; }
    }
}
