//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMCRECEIVERTHRESHOLD
    {
        public decimal PROJECTNO { get; set; }
        public decimal TYPEKEY { get; set; }
        public Nullable<decimal> TYPE_BW { get; set; }
        public Nullable<decimal> BANDWIDTH { get; set; }
        public string MODULATIONTYPE { get; set; }
        public Nullable<decimal> BITSPERSYMBOL { get; set; }
        public Nullable<decimal> POWMINGHZ { get; set; }
        public Nullable<decimal> POWMAXGHZ { get; set; }
        public Nullable<decimal> POWVALUEGHZ { get; set; }
    }
}
