//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARLAYAICAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARLAYAICAR()
        {
            this.CARRIERS = new HashSet<CARRIERS>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal CARLAYKEY { get; set; }
        public decimal CARRIERNUMBER { get; set; }
        public decimal MODIFYUSER { get; set; }
    
        public virtual AICAR AICAR { get; set; }
        public virtual CARLAY CARLAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRIERS> CARRIERS { get; set; }
    }
}
