//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARLAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARLAY()
        {
            this.CARLAYAICAR = new HashSet<CARLAYAICAR>();
            this.CARLAYDATA = new HashSet<CARLAYDATA>();
            this.CARRIERS = new HashSet<CARRIERS>();
            this.CELLAYCARLAY = new HashSet<CELLAYCARLAY>();
            this.PATTERN = new HashSet<PATTERN>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal CARLAYKEY { get; set; }
        public string IDNAME { get; set; }
        public string ABBREVIATION { get; set; }
        public Nullable<decimal> MAXCARRIERS { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> USEREUSEPATTERN { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> FREQBANDKEY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARLAYAICAR> CARLAYAICAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARLAYDATA> CARLAYDATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRIERS> CARRIERS { get; set; }
        public virtual FREQBAND FREQBAND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CELLAYCARLAY> CELLAYCARLAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATTERN> PATTERN { get; set; }
    }
}
