//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRIEDTRAFFICDETAIL
    {
        public decimal PROJECTNO { get; set; }
        public decimal CARTRAFDETPK { get; set; }
        public decimal SERVICEKEYFK { get; set; }
        public decimal TERMTYPEKEYFK { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
        public decimal PARENTFK { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<bool> PROTECTED { get; set; }
        public Nullable<decimal> THROUGHPUTDL { get; set; }
        public Nullable<decimal> INTRAHOTHROUGHPUTDL { get; set; }
        public Nullable<decimal> INTERHOTHROUGHPUTDL { get; set; }
        public Nullable<decimal> THROUGHPUTUL { get; set; }
        public Nullable<decimal> INTRAHOTHROUGHPUTUL { get; set; }
        public Nullable<decimal> INTERHOTHROUGHPUTUL { get; set; }
        public Nullable<decimal> TERMINALCOUNT { get; set; }
    
        public virtual TERMTYPE TERMTYPE { get; set; }
        public virtual LOGCELL LOGCELL { get; set; }
        public virtual LOGNODETYPE LOGNODETYPE { get; set; }
        public virtual TGSERVICE TGSERVICE { get; set; }
    }
}
