//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL
    {
        public decimal PROJECTNO { get; set; }
        public decimal BANDKEY { get; set; }
        public string CHANNAME { get; set; }
        public Nullable<decimal> LOFREQ { get; set; }
        public Nullable<decimal> HIFREQ { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal CHANNELKEY { get; set; }
    
        public virtual BAND BAND { get; set; }
    }
}
