//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTPERSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTACTPERSON()
        {
            this.PHONENUMBER = new HashSet<PHONENUMBER>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal PERSONKEY { get; set; }
        public string TITLE { get; set; }
        public string SURNAME { get; set; }
        public string FORENAME { get; set; }
        public string COMPANY { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> MODIFYUSER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONENUMBER> PHONENUMBER { get; set; }
    }
}
