//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COVCLASS
    {
        public decimal PROJECTNO { get; set; }
        public decimal COVCLASSKEY { get; set; }
        public decimal COVSCHEMAKEY { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> DATASET { get; set; }
        public Nullable<decimal> COLOUR { get; set; }
        public decimal MODIFYUSER { get; set; }
    }
}
