//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFREPEATER
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal LOGNODEPK { get; set; }
        public decimal DLOGNODEPK { get; set; }
        public string PHOTOFILE { get; set; }
        public string DPHOTOFILE { get; set; }
        public Nullable<decimal> HEXRADIUS { get; set; }
        public Nullable<decimal> DHEXRADIUS { get; set; }
        public Nullable<decimal> CABINKEY { get; set; }
        public Nullable<decimal> DCABINKEY { get; set; }
        public Nullable<decimal> BTSKEY { get; set; }
        public Nullable<decimal> DBTSKEY { get; set; }
        public Nullable<decimal> TOWERKEY { get; set; }
        public Nullable<decimal> DTOWERKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> RXSIGNAL { get; set; }
        public Nullable<decimal> DRXSIGNAL { get; set; }
        public Nullable<decimal> OUTPUTPOWER { get; set; }
        public Nullable<decimal> DOUTPUTPOWER { get; set; }
        public Nullable<decimal> CALCMETHOD { get; set; }
        public Nullable<decimal> DCALCMETHOD { get; set; }
        public Nullable<decimal> GAIN { get; set; }
        public Nullable<decimal> DGAIN { get; set; }
        public Nullable<decimal> RXTHRESHOLD { get; set; }
        public Nullable<decimal> DRXTHRESHOLD { get; set; }
        public Nullable<decimal> CELLKEY { get; set; }
        public Nullable<decimal> DCELLKEY { get; set; }
        public Nullable<decimal> BTSFIXED { get; set; }
        public Nullable<decimal> DBTSFIXED { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
        public decimal DLOGNODETYPEFK { get; set; }
    
        public virtual DIFFLOGNODE DIFFLOGNODE { get; set; }
    }
}
