//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFSITEADDRESS
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal ADDRESSKEY { get; set; }
        public decimal DADDRESSKEY { get; set; }
        public string ADDRESS1 { get; set; }
        public string DADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string DADDRESS2 { get; set; }
        public string TOWN { get; set; }
        public string DTOWN { get; set; }
        public string PROVINCE { get; set; }
        public string DPROVINCE { get; set; }
        public string STATE { get; set; }
        public string DSTATE { get; set; }
        public string POSTCODE { get; set; }
        public string DPOSTCODE { get; set; }
        public Nullable<decimal> PERSONKEY { get; set; }
        public Nullable<decimal> DPERSONKEY { get; set; }
        public string IDNAME { get; set; }
        public string DIDNAME { get; set; }
        public Nullable<decimal> DIRECTKEY { get; set; }
        public Nullable<decimal> DDIRECTKEY { get; set; }
        public Nullable<decimal> GNDHEIGHT { get; set; }
        public Nullable<decimal> DGNDHEIGHT { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<decimal> SRCHRAD { get; set; }
        public Nullable<decimal> DSRCHRAD { get; set; }
        public Nullable<decimal> SRCHOVERRIDEVIEW { get; set; }
        public Nullable<decimal> DSRCHOVERRIDEVIEW { get; set; }
        public Nullable<decimal> NOMINALID { get; set; }
        public Nullable<decimal> DNOMINALID { get; set; }
        public Nullable<decimal> TARGETSTATUS { get; set; }
        public Nullable<decimal> DTARGETSTATUS { get; set; }
        public string PROPERTYCODE { get; set; }
        public string DPROPERTYCODE { get; set; }
        public Nullable<decimal> LOCKSEARCHAREA { get; set; }
        public Nullable<decimal> DLOCKSEARCHAREA { get; set; }
        public string FLAGVALUE { get; set; }
        public string DFLAGVALUE { get; set; }
        public string COMMENTS { get; set; }
        public string DCOMMENTS { get; set; }
        public Nullable<decimal> MASTSPACE { get; set; }
        public Nullable<decimal> DMASTSPACE { get; set; }
        public Nullable<decimal> MTTR { get; set; }
        public Nullable<decimal> DMTTR { get; set; }
        public Nullable<decimal> BUILDINGHEIGHT { get; set; }
        public Nullable<decimal> DBUILDINGHEIGHT { get; set; }
        public string PANFILE { get; set; }
        public string DPANFILE { get; set; }
        public Nullable<decimal> ASSOCMAST { get; set; }
        public Nullable<decimal> DASSOCMAST { get; set; }
        public Nullable<decimal> MOUNTING { get; set; }
        public Nullable<decimal> DMOUNTING { get; set; }
        public Nullable<decimal> MAXHEIGHT { get; set; }
        public Nullable<decimal> DMAXHEIGHT { get; set; }
        public Nullable<decimal> MINHEIGHT { get; set; }
        public Nullable<decimal> DMINHEIGHT { get; set; }
        public string MASTEXCLUDED { get; set; }
        public string DMASTEXCLUDED { get; set; }
        public Nullable<decimal> ANTHEIGHTRULE { get; set; }
        public Nullable<decimal> DANTHEIGHTRULE { get; set; }
        public Nullable<decimal> ANTSTEPSIZE { get; set; }
        public Nullable<decimal> DANTSTEPSIZE { get; set; }
        public string ANTHEIGHTLIST { get; set; }
        public string DANTHEIGHTLIST { get; set; }
        public Nullable<decimal> ANTCOLOCATION { get; set; }
        public Nullable<decimal> DANTCOLOCATION { get; set; }
        public Nullable<decimal> MINAZIMDIFF { get; set; }
        public Nullable<decimal> DMINAZIMDIFF { get; set; }
        public Nullable<decimal> ANTSAMECELL { get; set; }
        public Nullable<decimal> DANTSAMECELL { get; set; }
        public Nullable<decimal> OPTIMISATIONSTATUS { get; set; }
        public Nullable<decimal> DOPTIMISATIONSTATUS { get; set; }
        public Nullable<decimal> GRIDCONSTRFLAGS { get; set; }
        public Nullable<decimal> DGRIDCONSTRFLAGS { get; set; }
        public string PRECANDIDATENAME { get; set; }
        public string DPRECANDIDATENAME { get; set; }
        public Nullable<decimal> DVISIBILITY { get; set; }
        public Nullable<decimal> DVISIBILITYGROUP { get; set; }
        public Nullable<decimal> VISIBILITY { get; set; }
        public Nullable<decimal> VISIBILITYGROUP { get; set; }
    }
}
