//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFBAND
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal BANDKEY { get; set; }
        public decimal DBANDKEY { get; set; }
        public string IDNAME { get; set; }
        public string DIDNAME { get; set; }
        public Nullable<decimal> BANDWIDTH { get; set; }
        public Nullable<decimal> DBANDWIDTH { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public decimal BANDDUPLEXMETHOD { get; set; }
        public decimal DBANDDUPLEXMETHOD { get; set; }
    }
}
