//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFREPEATERCELL
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal CELLKEY { get; set; }
        public decimal DCELLKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public decimal DFEEDERTYPE { get; set; }
        public decimal DLOGANTENNAFK { get; set; }
        public decimal DLOGNODEFK { get; set; }
        public decimal DSITEADDRESSFK { get; set; }
        public decimal FEEDERTYPE { get; set; }
        public decimal LOGANTENNAFK { get; set; }
        public decimal LOGNODEFK { get; set; }
        public decimal SITEADDRESSFK { get; set; }
    }
}
