//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFACTIVEOBJECTS
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal DFILTERKEY { get; set; }
        public decimal OBJECTKEY { get; set; }
        public decimal DOBJECTKEY { get; set; }
        public decimal ELEMENTTYPEKEY { get; set; }
        public decimal DELEMENTTYPEKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
