//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFLOGLTEFEEDER
    {
        public decimal FEEDPK { get; set; }
        public decimal DFEEDPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal LTECELLFK { get; set; }
        public decimal DLTECELLFK { get; set; }
        public decimal FEEDERTYPEFK { get; set; }
        public decimal DFEEDERTYPEFK { get; set; }
        public decimal MHAMPTYPEFK { get; set; }
        public decimal DMHAMPTYPEFK { get; set; }
        public Nullable<decimal> MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> MHGAIN_DB { get; set; }
        public Nullable<decimal> DMHGAIN_DB { get; set; }
        public Nullable<decimal> NOISE_DB { get; set; }
        public Nullable<decimal> DNOISE_DB { get; set; }
        public Nullable<decimal> TXDIV { get; set; }
        public Nullable<decimal> DTXDIV { get; set; }
        public Nullable<decimal> RXDIV { get; set; }
        public Nullable<decimal> DRXDIV { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> DLENGTH { get; set; }
        public Nullable<decimal> CORRFACTOR { get; set; }
        public Nullable<decimal> DCORRFACTOR { get; set; }
        public Nullable<decimal> MAXPAPOWER { get; set; }
        public Nullable<decimal> DMAXPAPOWER { get; set; }
        public Nullable<decimal> ULGAIN { get; set; }
        public Nullable<decimal> DULGAIN { get; set; }
        public Nullable<decimal> DLGAIN { get; set; }
        public Nullable<decimal> DDLGAIN { get; set; }
        public Nullable<decimal> OTHERLOSSES { get; set; }
        public Nullable<decimal> DOTHERLOSSES { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public decimal ADDRESSFK { get; set; }
        public decimal DADDRESSFK { get; set; }
        public decimal DLOGANTENNAFK { get; set; }
        public decimal LOGANTENNAFK { get; set; }
    }
}
