//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFREFLECTOR
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal REFLECTORPK { get; set; }
        public decimal DREFLECTORPK { get; set; }
        public decimal PRLINKENDFK { get; set; }
        public decimal DPRLINKENDFK { get; set; }
        public decimal PRLINKFK { get; set; }
        public decimal DPRLINKFK { get; set; }
        public decimal LINKFK { get; set; }
        public decimal DLINKFK { get; set; }
        public Nullable<decimal> CENTREHEIGHT { get; set; }
        public Nullable<decimal> DCENTREHEIGHT { get; set; }
        public Nullable<decimal> TILT { get; set; }
        public Nullable<decimal> DTILT { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> DHEIGHT { get; set; }
        public Nullable<decimal> REFWIDTH { get; set; }
        public Nullable<decimal> DREFWIDTH { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<decimal> COORDTYPE { get; set; }
        public Nullable<decimal> DCOORDTYPE { get; set; }
        public Nullable<decimal> AREA { get; set; }
        public Nullable<decimal> AZIMUTH { get; set; }
        public Nullable<decimal> DAREA { get; set; }
        public Nullable<decimal> DAZIMUTH { get; set; }
        public Nullable<decimal> DEFFECTIVEAREA { get; set; }
        public Nullable<decimal> DFACE { get; set; }
        public Nullable<decimal> DINCLUDED { get; set; }
        public Nullable<decimal> DPASSIVEGAIN { get; set; }
        public Nullable<decimal> DPOINTING { get; set; }
        public Nullable<decimal> DVERTICAL { get; set; }
        public Nullable<decimal> EFFECTIVEAREA { get; set; }
        public Nullable<decimal> FACE { get; set; }
        public Nullable<decimal> INCLUDED { get; set; }
        public Nullable<decimal> PASSIVEGAIN { get; set; }
        public Nullable<decimal> POINTING { get; set; }
        public Nullable<decimal> VERTICAL { get; set; }
    }
}
