//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFLOGIS95CAR
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal IS95CARPK { get; set; }
        public decimal DIS95CARPK { get; set; }
        public decimal LOGBSFK { get; set; }
        public decimal DLOGBSFK { get; set; }
        public decimal IS95CARRIERDATAFK { get; set; }
        public decimal DIS95CARRIERDATAFK { get; set; }
        public Nullable<decimal> NUMPOOLEDTRAFFCHANELEMS { get; set; }
        public Nullable<decimal> DNUMPOOLEDTRAFFCHANELEMS { get; set; }
        public Nullable<decimal> NUMTOTALTRAFFCHANELEMS { get; set; }
        public Nullable<decimal> DNUMTOTALTRAFFCHANELEMS { get; set; }
        public Nullable<decimal> TRAFFCHANDATARATE { get; set; }
        public Nullable<decimal> DTRAFFCHANDATARATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public decimal DLOGNODETYPEFK { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
    }
}
