//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFCIOBJ
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal CIOBJKEY { get; set; }
        public decimal DCIOBJKEY { get; set; }
        public string IDNAME { get; set; }
        public string DIDNAME { get; set; }
        public Nullable<decimal> VICTIMCARRIERBW { get; set; }
        public Nullable<decimal> DVICTIMCARRIERBW { get; set; }
        public Nullable<decimal> INTFCARRIERBW { get; set; }
        public Nullable<decimal> DINTFCARRIERBW { get; set; }
        public Nullable<decimal> VICTIMRADIOEQUIP { get; set; }
        public Nullable<decimal> DVICTIMRADIOEQUIP { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> DPERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<decimal> DUSERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<decimal> VICTIMMODTYPE { get; set; }
        public Nullable<decimal> DVICTIMMODTYPE { get; set; }
        public Nullable<decimal> INTFRADIOEQUIP { get; set; }
        public Nullable<decimal> DINTFRADIOEQUIP { get; set; }
        public Nullable<decimal> INTFMODTYPE { get; set; }
        public Nullable<decimal> DINTFMODTYPE { get; set; }
        public Nullable<decimal> DINTFNOOFCHANNELS { get; set; }
        public Nullable<decimal> VICTIMCHANNELCPCTYTYPE { get; set; }
        public Nullable<decimal> INTFSINGLEVALUE { get; set; }
        public Nullable<decimal> DINTFSINGLEVALUE { get; set; }
        public Nullable<decimal> INTFNOOFCHANNELS { get; set; }
        public Nullable<decimal> DINTFCHANNELCPCTYTYPE { get; set; }
        public Nullable<decimal> VICTIMSINGLEVALUE { get; set; }
        public Nullable<decimal> VICTIMNOOFCHANNELS { get; set; }
        public Nullable<decimal> DVICTIMNOOFCHANNELS { get; set; }
        public Nullable<decimal> INTFCHANNELCPCTYTYPE { get; set; }
        public Nullable<decimal> DVICTIMSINGLEVALUE { get; set; }
        public Nullable<decimal> DVICTIMCHANNELCPCTYTYPE { get; set; }
    }
}
