//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFTGSERVBIT
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal SERVICEKEY { get; set; }
        public decimal DSERVICEKEY { get; set; }
        public decimal BITRATEKEY { get; set; }
        public decimal DBITRATEKEY { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> DWEIGHT { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> DCREATEUSER { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> CP0 { get; set; }
        public Nullable<decimal> DCP0 { get; set; }
        public Nullable<decimal> CP1 { get; set; }
        public Nullable<decimal> DCP1 { get; set; }
        public Nullable<decimal> CP2 { get; set; }
        public Nullable<decimal> DCP2 { get; set; }
        public Nullable<decimal> CP3 { get; set; }
        public Nullable<decimal> DCP3 { get; set; }
        public Nullable<decimal> CP4 { get; set; }
        public Nullable<decimal> DCP4 { get; set; }
        public Nullable<decimal> CP5 { get; set; }
        public Nullable<decimal> DCP5 { get; set; }
        public Nullable<decimal> CP6 { get; set; }
        public Nullable<decimal> DCP6 { get; set; }
        public Nullable<decimal> CP7 { get; set; }
        public Nullable<decimal> DCP7 { get; set; }
        public Nullable<decimal> CP8 { get; set; }
        public Nullable<decimal> DCP8 { get; set; }
        public Nullable<decimal> CP9 { get; set; }
        public Nullable<decimal> DCP9 { get; set; }
        public Nullable<decimal> CP10 { get; set; }
        public Nullable<decimal> DCP10 { get; set; }
        public Nullable<decimal> CP11 { get; set; }
        public Nullable<decimal> DCP11 { get; set; }
        public Nullable<decimal> CP12 { get; set; }
        public Nullable<decimal> DCP12 { get; set; }
        public Nullable<decimal> CP13 { get; set; }
        public Nullable<decimal> DCP13 { get; set; }
        public Nullable<decimal> CP14 { get; set; }
        public Nullable<decimal> DCP14 { get; set; }
        public Nullable<decimal> CP15 { get; set; }
        public Nullable<decimal> DCP15 { get; set; }
        public Nullable<decimal> CP16 { get; set; }
        public Nullable<decimal> DCP16 { get; set; }
        public Nullable<decimal> CP17 { get; set; }
        public Nullable<decimal> DCP17 { get; set; }
        public Nullable<decimal> CP18 { get; set; }
        public Nullable<decimal> DCP18 { get; set; }
        public Nullable<decimal> CP19 { get; set; }
        public Nullable<decimal> DCP19 { get; set; }
        public Nullable<decimal> CP20 { get; set; }
        public Nullable<decimal> DCP20 { get; set; }
        public Nullable<decimal> CP21 { get; set; }
        public Nullable<decimal> DCP21 { get; set; }
        public Nullable<decimal> CP22 { get; set; }
        public Nullable<decimal> DCP22 { get; set; }
        public Nullable<decimal> CP23 { get; set; }
        public Nullable<decimal> DCP23 { get; set; }
        public Nullable<decimal> CP24 { get; set; }
        public Nullable<decimal> DCP24 { get; set; }
        public Nullable<decimal> CP25 { get; set; }
        public Nullable<decimal> DCP25 { get; set; }
        public Nullable<decimal> CP26 { get; set; }
        public Nullable<decimal> DCP26 { get; set; }
        public Nullable<decimal> CP27 { get; set; }
        public Nullable<decimal> DCP27 { get; set; }
        public Nullable<decimal> CP28 { get; set; }
        public Nullable<decimal> DCP28 { get; set; }
        public Nullable<decimal> CP29 { get; set; }
        public Nullable<decimal> DCP29 { get; set; }
        public Nullable<decimal> CP30 { get; set; }
        public Nullable<decimal> DCP30 { get; set; }
        public Nullable<decimal> CP31 { get; set; }
        public Nullable<decimal> DCP31 { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public decimal PWRACT { get; set; }
        public decimal DPWRACT { get; set; }
        public decimal TPTACT { get; set; }
        public decimal DTPTACT { get; set; }
        public decimal RESACT { get; set; }
        public decimal DRESACT { get; set; }
    }
}
