//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFLOGWIFICELLCAR
    {
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal CELLCARRIERPK { get; set; }
        public decimal DCELLCARRIERPK { get; set; }
        public decimal WIFICELLFK { get; set; }
        public decimal DWIFICELLFK { get; set; }
        public decimal CARRIERFK { get; set; }
        public decimal DCARRIERFK { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> TXPOWER { get; set; }
        public Nullable<decimal> DTXPOWER { get; set; }
        public Nullable<decimal> DLCVRGTHOLD { get; set; }
        public Nullable<decimal> DDLCVRGTHOLD { get; set; }
        public Nullable<decimal> DLDISTANCETHOLD { get; set; }
        public Nullable<decimal> DDLDISTANCETHOLD { get; set; }
        public Nullable<decimal> DLCAPACITY { get; set; }
        public Nullable<decimal> DDLCAPACITY { get; set; }
        public Nullable<decimal> DLRESVDCAPACITY { get; set; }
        public Nullable<decimal> DDLRESVDCAPACITY { get; set; }
        public Nullable<decimal> ULCAPACITY { get; set; }
        public Nullable<decimal> DULCAPACITY { get; set; }
        public Nullable<decimal> ULRESVDCAPACITY { get; set; }
        public Nullable<decimal> DULRESVDCAPACITY { get; set; }
        public Nullable<decimal> MAXUSERS { get; set; }
        public Nullable<decimal> DMAXUSERS { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
    }
}
