//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFGENREPEATER
    {
        public decimal LOGNODEPK { get; set; }
        public decimal DLOGNODEPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal DPROJECTNO { get; set; }
        public decimal CELLFK { get; set; }
        public decimal DCELLFK { get; set; }
        public Nullable<decimal> DLGAIN { get; set; }
        public Nullable<decimal> DDLGAIN { get; set; }
        public Nullable<decimal> ULGAIN { get; set; }
        public Nullable<decimal> DULGAIN { get; set; }
        public Nullable<decimal> ULNOISEFACTOR { get; set; }
        public Nullable<decimal> DULNOISEFACTOR { get; set; }
        public Nullable<decimal> MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
        public decimal DLOGNODETYPEFK { get; set; }
        public decimal CALCMETHOD { get; set; }
        public decimal DCALCMETHOD { get; set; }
    
        public virtual DIFFLOGNODE DIFFLOGNODE { get; set; }
    }
}
