//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIFFACTIVEATTRIB
    {
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> DPROJECTNO { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal DFILTERKEY { get; set; }
        public decimal RULEKEY { get; set; }
        public decimal DRULEKEY { get; set; }
        public decimal ACTIVEATTRIBUTEKEY { get; set; }
        public decimal DACTIVEATTRIBUTEKEY { get; set; }
        public decimal ATTRIBUTENUM { get; set; }
        public decimal DATTRIBUTENUM { get; set; }
        public decimal PICKEDOBJECTKEY { get; set; }
        public Nullable<decimal> DPICKEDOBJECTKEY { get; set; }
        public Nullable<decimal> ELEMENTTYPEKEY { get; set; }
        public Nullable<decimal> DELEMENTTYPEKEY { get; set; }
        public Nullable<decimal> BOOL { get; set; }
        public Nullable<decimal> DBOOL { get; set; }
        public Nullable<decimal> NUMBERA { get; set; }
        public Nullable<decimal> DNUMBERA { get; set; }
        public Nullable<decimal> NUMBERB { get; set; }
        public Nullable<decimal> DNUMBERB { get; set; }
        public string STRING { get; set; }
        public string DSTRING { get; set; }
        public string CELLLAYERID { get; set; }
        public string DCELLLAYERID { get; set; }
        public string CARLAYERID { get; set; }
        public string DCARLAYERID { get; set; }
        public Nullable<decimal> OBJECTKEY { get; set; }
        public Nullable<decimal> DOBJECTKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal DMODIFYUSER { get; set; }
        public Nullable<decimal> DIFFSTATE { get; set; }
        public Nullable<decimal> DTECHNOLOGY { get; set; }
        public Nullable<decimal> TECHNOLOGY { get; set; }
        public decimal DRDATE { get; set; }
        public decimal DRTIME { get; set; }
        public decimal RDATE { get; set; }
        public decimal RTIME { get; set; }
    }
}
