//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENT_ACTIVELOGON_DATA
    {
        public decimal USRKEY { get; set; }
        public string USERID { get; set; }
        public Nullable<decimal> PROJECTNO { get; set; }
        public Nullable<decimal> SHAREDNO { get; set; }
        public string SESSIONID { get; set; }
        public string HOSTNAME { get; set; }
        public decimal PID { get; set; }
        public bool RW { get; set; }
        public System.DateTime DATETIME { get; set; }
        public System.DateTime STARTTIME { get; set; }
        public string ISDBA { get; set; }
        public string OS_USER { get; set; }
        public string IP_ADDRESS { get; set; }
        public string AUTHTYPE { get; set; }
        public Nullable<bool> LOCKED { get; set; }
        public string MODETYPE { get; set; }
        public Nullable<decimal> CHILDUSRKEY { get; set; }
        public Nullable<bool> RW_ALLPROJECTS { get; set; }
        public string PROCESSNAME { get; set; }
    }
}
