//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELDSTABLE
    {
        public string ACTABLENAME { get; set; }
        public string ACFIELDNAME { get; set; }
        public string ACFIELDTYPE { get; set; }
        public Nullable<decimal> ACFIELDLENGTH { get; set; }
    }
}
