//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILTERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILTERS()
        {
            this.ACTIVEATTRIB = new HashSet<ACTIVEATTRIB>();
            this.ACTIVEELEMENTS = new HashSet<ACTIVEELEMENTS>();
            this.ACTIVEFLAGS = new HashSet<ACTIVEFLAGS>();
            this.ACTIVEOBJECTS = new HashSet<ACTIVEOBJECTS>();
            this.ACTIVEPOLYGONS = new HashSet<ACTIVEPOLYGONS>();
            this.ACTIVEWFS = new HashSet<ACTIVEWFS>();
            this.LOGICALOPS = new HashSet<LOGICALOPS>();
            this.RULES = new HashSet<RULES>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal TYPE { get; set; }
        public string FILTERID { get; set; }
        public decimal PERMISSION { get; set; }
        public decimal CREATEUSER { get; set; }
        public decimal USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<decimal> PARENTKEY { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> LASTUSEDDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEATTRIB> ACTIVEATTRIB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEELEMENTS> ACTIVEELEMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEFLAGS> ACTIVEFLAGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEOBJECTS> ACTIVEOBJECTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEPOLYGONS> ACTIVEPOLYGONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEWFS> ACTIVEWFS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGICALOPS> LOGICALOPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RULES> RULES { get; set; }
    }
}
