//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPCARRIER
    {
        public decimal PROJECTNO { get; set; }
        public decimal GROUPKEY { get; set; }
        public decimal CARRIERNUMBER { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal PATTERNKEY { get; set; }
    
        public virtual PATTERNGROUP PATTERNGROUP { get; set; }
    }
}
