//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTF
    {
        public decimal PROJECTNO { get; set; }
        public decimal INTFKEY { get; set; }
        public string IDNAME { get; set; }
        public Nullable<decimal> NUMWEIGHTS { get; set; }
        public Nullable<decimal> STARTVALUE { get; set; }
        public Nullable<decimal> CAOFFSET { get; set; }
    }
}
