//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINKTYPE
    {
        public decimal PROJECTNO { get; set; }
        public decimal LINKTYPEKEY { get; set; }
        public string IDNAME { get; set; }
        public Nullable<decimal> BEARER { get; set; }
        public string MANUFACTURER { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> FIBRES { get; set; }
        public Nullable<decimal> INSTALLCOST { get; set; }
        public Nullable<decimal> MAINTENCOST { get; set; }
        public Nullable<decimal> RENTALCOSTKM { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
    }
}
