//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINKATTACH
    {
        public decimal PROJECTNO { get; set; }
        public decimal ATTACHKEY { get; set; }
        public decimal LINKKEY { get; set; }
        public string FILENAME { get; set; }
        public string COMMENTS { get; set; }
        public decimal MODIFYUSER { get; set; }
    
        public virtual LINK LINK { get; set; }
    }
}
