//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGCONNROUTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGCONNROUTE()
        {
            this.LOGCONNRTHOP = new HashSet<LOGCONNRTHOP>();
        }
    
        public decimal CONNROUTEPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal LOGCONNFK { get; set; }
        public Nullable<decimal> INDEXNO { get; set; }
        public string USERCOMMENT { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
    
        public virtual LOGCONNECTION LOGCONNECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGCONNRTHOP> LOGCONNRTHOP { get; set; }
    }
}
