//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIS95CAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGIS95CAR()
        {
            this.LOGIS95SECCAR = new HashSet<LOGIS95SECCAR>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal IS95CARPK { get; set; }
        public decimal LOGBSFK { get; set; }
        public decimal IS95CARRIERDATAFK { get; set; }
        public Nullable<decimal> NUMPOOLEDTRAFFCHANELEMS { get; set; }
        public Nullable<decimal> NUMTOTALTRAFFCHANELEMS { get; set; }
        public Nullable<decimal> TRAFFCHANDATARATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
    
        public virtual IS95CARRIER IS95CARRIER { get; set; }
        public virtual MUNODE MUNODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIS95SECCAR> LOGIS95SECCAR { get; set; }
    }
}
