//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGNODEBTYPE
    {
        public decimal PROJECTNO { get; set; }
        public decimal NODEBTYPEKEY { get; set; }
        public string IDNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string PHOTOFILE { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<decimal> MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> EQUIPICONKEY { get; set; }
        public Nullable<decimal> SUPPLIERKEY { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> RES1NAMEKEY { get; set; }
        public Nullable<decimal> RES1PROPS { get; set; }
        public Nullable<decimal> RES1ULTOT { get; set; }
        public Nullable<decimal> RES1DLTOT { get; set; }
        public Nullable<decimal> RES1ULPRI { get; set; }
        public Nullable<decimal> RES1DLPRI { get; set; }
        public Nullable<decimal> RES1ULHO { get; set; }
        public Nullable<decimal> RES1DLHO { get; set; }
        public Nullable<decimal> RES2NAMEKEY { get; set; }
        public Nullable<decimal> RES2PROPS { get; set; }
        public Nullable<decimal> RES2ULTOT { get; set; }
        public Nullable<decimal> RES2DLTOT { get; set; }
        public Nullable<decimal> RES2ULPRI { get; set; }
        public Nullable<decimal> RES2DLPRI { get; set; }
        public Nullable<decimal> RES2ULHO { get; set; }
        public Nullable<decimal> RES2DLHO { get; set; }
        public Nullable<decimal> RES3NAMEKEY { get; set; }
        public Nullable<decimal> RES3PROPS { get; set; }
        public Nullable<decimal> RES3ULTOT { get; set; }
        public Nullable<decimal> RES3DLTOT { get; set; }
        public Nullable<decimal> RES3ULPRI { get; set; }
        public Nullable<decimal> RES3DLPRI { get; set; }
        public Nullable<decimal> RES3ULHO { get; set; }
        public Nullable<decimal> RES3DLHO { get; set; }
        public Nullable<decimal> PERDLTRAFPOW { get; set; }
        public Nullable<decimal> PERNOISERISELIM { get; set; }
        public Nullable<decimal> AUTOTXCALC { get; set; }
        public bool OTSRSUPPORT { get; set; }
    }
}
