//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGNODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGNODE()
        {
            this.BSC = new HashSet<BSC>();
            this.DISTRIBUTION = new HashSet<DISTRIBUTION>();
            this.GENREPEATER = new HashSet<GENREPEATER>();
            this.GRIDCONFIG = new HashSet<GRIDCONFIG>();
            this.LOGATTACHMENT = new HashSet<LOGATTACHMENT>();
            this.LOGCELL = new HashSet<LOGCELL>();
            this.LOGCONNECTION = new HashSet<LOGCONNECTION>();
            this.LOGCONNECTION1 = new HashSet<LOGCONNECTION>();
            this.LOGIS95BSC = new HashSet<LOGIS95BSC>();
            this.LOGIS95MSC = new HashSet<LOGIS95MSC>();
            this.LOGMME = new HashSet<LOGMME>();
            this.LOGNODETRAFFIC = new HashSet<LOGNODETRAFFIC>();
            this.LOGRNC = new HashSet<LOGRNC>();
            this.LOGSAEGW = new HashSet<LOGSAEGW>();
            this.MSC = new HashSet<MSC>();
            this.REPEATER = new HashSet<REPEATER>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal LOGNODEPK { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
        public decimal LOGNETWORKFK { get; set; }
        public decimal ADDRESSFK { get; set; }
        public string IDNAME { get; set; }
        public string NAME { get; set; }
        public string NAME2 { get; set; }
        public string USERCOMMENT { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> HASCONSTRAINTS { get; set; }
        public Nullable<decimal> CONSTRFLAGS { get; set; }
        public Nullable<decimal> MINSECTORS { get; set; }
        public Nullable<decimal> MAXSECTORS { get; set; }
        public Nullable<decimal> NETWORKLEVEL { get; set; }
        public Nullable<decimal> SIGNALLINGOVERHEAD { get; set; }
        public Nullable<decimal> VISIBILITY { get; set; }
        public Nullable<decimal> VISIBILITYGROUP { get; set; }
        public decimal SUBTYPEFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BSC> BSC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISTRIBUTION> DISTRIBUTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENREPEATER> GENREPEATER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRIDCONFIG> GRIDCONFIG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGATTACHMENT> LOGATTACHMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGCELL> LOGCELL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGCONNECTION> LOGCONNECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGCONNECTION> LOGCONNECTION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIS95BSC> LOGIS95BSC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIS95MSC> LOGIS95MSC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGMME> LOGMME { get; set; }
        public virtual LOGNETWORK LOGNETWORK { get; set; }
        public virtual LOGNODETYPE LOGNODETYPE { get; set; }
        public virtual SITEADDRESS SITEADDRESS { get; set; }
        public virtual LOGNODETYPE LOGNODETYPE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGNODETRAFFIC> LOGNODETRAFFIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGRNC> LOGRNC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGSAEGW> LOGSAEGW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSC> MSC { get; set; }
        public virtual MUNODE MUNODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPEATER> REPEATER { get; set; }
    }
}
