//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGNODETRAFFIC
    {
        public decimal TRAFFICPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal LOGNODEFK { get; set; }
        public decimal LOGCONNFK { get; set; }
        public Nullable<decimal> SYMMETRIC { get; set; }
        public Nullable<decimal> BITRATEDIRAKBS { get; set; }
        public Nullable<decimal> BITRATEDIRBKBS { get; set; }
        public Nullable<decimal> NUMSUBSCRIBERS { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
    
        public virtual LOGNODE LOGNODE { get; set; }
        public virtual LOGNODETYPE LOGNODETYPE { get; set; }
    }
}
