//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGNETWORK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGNETWORK()
        {
            this.LOGNETWORK1 = new HashSet<LOGNETWORK>();
            this.LOGNODE = new HashSet<LOGNODE>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal LOGNETWORKPK { get; set; }
        public Nullable<decimal> NETWORKTYPEFK { get; set; }
        public decimal PARENTFK { get; set; }
        public string USERCOMMENT { get; set; }
        public string IDNAME { get; set; }
        public string SUBNETID { get; set; }
        public string MECONTEXTID { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> VISIBILITY { get; set; }
        public Nullable<decimal> VISIBILITYGROUP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGNETWORK> LOGNETWORK1 { get; set; }
        public virtual LOGNETWORK LOGNETWORK2 { get; set; }
        public virtual LOGNODETYPE LOGNODETYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGNODE> LOGNODE { get; set; }
        public virtual LOGPLMN LOGPLMN { get; set; }
    }
}
