//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWANTENNATYPE
    {
        public decimal PROJECTNO { get; set; }
        public decimal MWANTENNAKEY { get; set; }
        public string IDNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string PHOTOFILE { get; set; }
        public Nullable<decimal> GAIN { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
        public Nullable<decimal> FRONTTOBACKRATIO { get; set; }
        public Nullable<decimal> MINOPFREQ { get; set; }
        public Nullable<decimal> MAXOPFREQ { get; set; }
        public Nullable<decimal> DIAMETER { get; set; }
        public Nullable<decimal> GAINTYPE { get; set; }
        public Nullable<decimal> TILTTYPE { get; set; }
        public Nullable<decimal> POLARISATION { get; set; }
        public string MANUFACTURER { get; set; }
        public Nullable<decimal> EQUIPICONKEY { get; set; }
        public Nullable<decimal> SUPPLIERKEY { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> PARENTKEY { get; set; }
        public string MASK { get; set; }
        public Nullable<decimal> MASKSTYLE { get; set; }
        public string FCCID { get; set; }
        public string PATTERNID { get; set; }
        public Nullable<decimal> HALFPOWERBEAMWIDTH { get; set; }
    }
}
