//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIORUSERPRIVEXTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRIORUSERPRIVEXTYPE()
        {
            this.PRIORUSERPRIVEX = new HashSet<PRIORUSERPRIVEX>();
        }
    
        public decimal PERMISSIONTYPEPK { get; set; }
        public string SHORTNAME { get; set; }
        public string USERCOMMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIORUSERPRIVEX> PRIORUSERPRIVEX { get; set; }
    }
}
