//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRLREF
    {
        public decimal PROJECTNO { get; set; }
        public decimal PRLPK { get; set; }
        public decimal LINKPK { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal OBJECTTYPE { get; set; }
        public Nullable<decimal> LEGNO { get; set; }
    
        public virtual LINK LINK { get; set; }
        public virtual PRLLINK PRLLINK { get; set; }
    }
}
