//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIOEQUIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RADIOEQUIP()
        {
            this.RADIOAMCTHRESHOLD = new HashSet<RADIOAMCTHRESHOLD>();
            this.RADIOMASK = new HashSet<RADIOMASK>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal RADIOEQUIPKEY { get; set; }
        public string IDNAME { get; set; }
        public string MANUFACTURER { get; set; }
        public Nullable<decimal> THRESH1BER { get; set; }
        public Nullable<decimal> THRESH2BER { get; set; }
        public Nullable<decimal> MOUSINGLE { get; set; }
        public Nullable<decimal> MOUHOTSB { get; set; }
        public Nullable<decimal> MOUCOLDSB { get; set; }
        public Nullable<decimal> MOUONEPLUSONE { get; set; }
        public Nullable<decimal> MTBF { get; set; }
        public Nullable<decimal> FKTB { get; set; }
        public Nullable<decimal> PROTECTED { get; set; }
        public Nullable<decimal> FREQBAND { get; set; }
        public Nullable<decimal> MINOPFREQ { get; set; }
        public Nullable<decimal> MAXOPFREQ { get; set; }
        public Nullable<decimal> FREQBW { get; set; }
        public string MODULATION { get; set; }
        public string DESCRIPTION { get; set; }
        public string PHOTOFILE { get; set; }
        public Nullable<decimal> SELECTIVE { get; set; }
        public Nullable<decimal> APPROXSELECTIVE { get; set; }
        public Nullable<decimal> DISPERSIVE { get; set; }
        public Nullable<decimal> EQUALISER { get; set; }
        public Nullable<decimal> USEMSM { get; set; }
        public Nullable<decimal> TXMOUSINGLE { get; set; }
        public Nullable<decimal> TXMOUHOTSB { get; set; }
        public Nullable<decimal> TXMOUCOLDSB { get; set; }
        public Nullable<decimal> TXMOUONEPLUSONE { get; set; }
        public Nullable<decimal> RADIOTYPE { get; set; }
        public Nullable<decimal> DUPMETHOD { get; set; }
        public Nullable<decimal> MOUONEPLUSTWO { get; set; }
        public Nullable<decimal> TXMOUONEPLUSTWO { get; set; }
        public string FAMILY { get; set; }
        public Nullable<decimal> SUPPLIERKEY { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> TRAFFICCHANNEL { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> NOISEFIG { get; set; }
        public Nullable<decimal> NOISETEMP { get; set; }
        public Nullable<decimal> OVERRIDE { get; set; }
        public Nullable<decimal> TXMOUSINGLENM { get; set; }
        public Nullable<decimal> MOUSINGLENM { get; set; }
        public Nullable<decimal> ENABLEATPC { get; set; }
        public Nullable<decimal> SINGLEVALUE { get; set; }
        public Nullable<decimal> MULTIRADIO { get; set; }
        public Nullable<decimal> MOUDUALNM { get; set; }
        public Nullable<decimal> TXMOUDUALNM { get; set; }
        public Nullable<decimal> MODTYPEKEY { get; set; }
        public Nullable<decimal> PARENTKEY { get; set; }
        public Nullable<decimal> USEAMC { get; set; }
        public Nullable<decimal> SELECTEDAMC { get; set; }
        public string AMCTYPES { get; set; }
        public Nullable<decimal> MAXCAPACITY { get; set; }
        public decimal OPERATINGMODE { get; set; }
        public Nullable<decimal> BITSPERBLOCK { get; set; }
        public Nullable<decimal> BLOCKSPERSECOND { get; set; }
        public Nullable<decimal> RBERTHRESHOLD { get; set; }
        public string RESIDUALBER { get; set; }
        public string SBER { get; set; }
        public Nullable<decimal> SESTHRESHOLD { get; set; }
        public Nullable<decimal> FRAMESIZE { get; set; }
        public Nullable<decimal> LATENCY { get; set; }
        public Nullable<decimal> TRANSITIONGAP { get; set; }
        public Nullable<decimal> SAMEMODPARAMS { get; set; }
        public Nullable<decimal> ENABLEXPIC { get; set; }
        public Nullable<decimal> CHANNELCAPACITYENUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADIOAMCTHRESHOLD> RADIOAMCTHRESHOLD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADIOMASK> RADIOMASK { get; set; }
    }
}
