//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_COLUMNS
    {
        public string TABLE_NAME { get; set; }
        public string CONSTRAINT_NAME { get; set; }
        public string CONSTRAINT_TYPE { get; set; }
        public string COLUMN_NAME { get; set; }
        public Nullable<decimal> POSITION { get; set; }
        public string R_CONSTRAINT_NAME { get; set; }
        public string R_TABLE { get; set; }
        public string R_COLUMN { get; set; }
        public Nullable<decimal> R_POS { get; set; }
        public string TABLE_TYPE { get; set; }
    }
}
