//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RULES()
        {
            this.ACTIVEATTRIB = new HashSet<ACTIVEATTRIB>();
            this.ACTIVEELEMENTS = new HashSet<ACTIVEELEMENTS>();
            this.ACTIVEFLAGS = new HashSet<ACTIVEFLAGS>();
            this.ACTIVEPOLYGONS = new HashSet<ACTIVEPOLYGONS>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal RNOT { get; set; }
        public decimal RULEKEY { get; set; }
        public decimal RULETYPEKEY { get; set; }
        public decimal ATTRIBUTETYPEKEY { get; set; }
        public decimal LOGICALOPKEY { get; set; }
        public Nullable<decimal> ELEMENTTYPEKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEATTRIB> ACTIVEATTRIB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEELEMENTS> ACTIVEELEMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEFLAGS> ACTIVEFLAGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEPOLYGONS> ACTIVEPOLYGONS { get; set; }
        public virtual ACTIVEWFS ACTIVEWFS { get; set; }
        public virtual FILTERS FILTERS { get; set; }
        public virtual LOGICALOPS LOGICALOPS { get; set; }
        public virtual RULETYPES RULETYPES { get; set; }
    }
}
