//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPURREF
    {
        public decimal PROJECTNO { get; set; }
        public decimal SPURPK { get; set; }
        public decimal LINKPK { get; set; }
        public decimal MODIFYUSER { get; set; }
    
        public virtual SPURLINK SPURLINK { get; set; }
    }
}
