//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGCLUTPATHLOSS
    {
        public decimal PROJECTNO { get; set; }
        public decimal KEY { get; set; }
        public string CODE { get; set; }
        public decimal TECHNOLOGYTYPE { get; set; }
        public Nullable<decimal> FADEIND { get; set; }
        public Nullable<decimal> FADEOUT { get; set; }
        public Nullable<decimal> INDLOSS { get; set; }
        public Nullable<decimal> ORTHLOSS { get; set; }
        public Nullable<decimal> INDPER { get; set; }
        public Nullable<decimal> CLUTCON { get; set; }
        public Nullable<decimal> ANGULARSPREAD { get; set; }
        public decimal ULSDSINRADJ { get; set; }
        public decimal DLSDSINRADJ { get; set; }
        public decimal DLSMRATEGAIN { get; set; }
        public decimal DLSMEBNOADJ { get; set; }
        public decimal DLMUMIMOSINROFFSET { get; set; }
        public decimal DLSMSINROFFSET { get; set; }
        public decimal ULMUMIMOSINROFFSET { get; set; }
        public decimal ULSMRATEGAIN { get; set; }
        public decimal ULSMSINROFFSET { get; set; }
    }
}
