//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGSERVBITCARREINF
    {
        public decimal PROJECTNO { get; set; }
        public decimal SERVICEKEY { get; set; }
        public decimal BITRATEKEY { get; set; }
        public decimal CARRIERKEY { get; set; }
        public decimal MINRE_TX1 { get; set; }
        public decimal MAXRE_TX1 { get; set; }
        public decimal MINRE_TX2 { get; set; }
        public decimal MAXRE_TX2 { get; set; }
        public decimal MINRE_TX2PLUS { get; set; }
        public decimal MAXRE_TX2PLUS { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public decimal MODIFYUSER { get; set; }
    }
}
