//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_800_FLAGGROUPS
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public decimal FLAGGROUPKEY { get; set; }
        public string FLAGGROUPID { get; set; }
        public decimal FIELDTYPE { get; set; }
        public decimal FLAGGROUPLOCKED { get; set; }
        public decimal RESETONCLONING { get; set; }
    }
}
