//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_90_GROUPCARRIER
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public Nullable<decimal> GROUPKEY { get; set; }
        public Nullable<decimal> CARRIERNUMBER { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PATTERNKEY { get; set; }
    }
}
