//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_620_PRIORGROUPSRM
    {
        public decimal GRPKEY { get; set; }
        public string GRP { get; set; }
        public string GRPCOM { get; set; }
        public Nullable<decimal> PROJECTPRIV { get; set; }
        public Nullable<decimal> PN { get; set; }
    }
}
