//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_91_BCF
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public decimal BCFKEY { get; set; }
        public decimal SITEKEY { get; set; }
        public string IDNAME { get; set; }
        public Nullable<decimal> BCFID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<decimal> BCFTYPEKEY { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
    }
}
