//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_90_LOGWIFICELLCAR
    {
        public decimal PROJECTNO { get; set; }
        public decimal CELLCARRIERPK { get; set; }
        public decimal WIFICELLFK { get; set; }
        public decimal CARRIERFK { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> TXPOWER { get; set; }
        public Nullable<decimal> DLCVRGTHOLD { get; set; }
        public Nullable<decimal> DLDISTANCETHOLD { get; set; }
        public Nullable<decimal> DLCAPACITY { get; set; }
        public Nullable<decimal> DLRESVDCAPACITY { get; set; }
        public Nullable<decimal> ULCAPACITY { get; set; }
        public Nullable<decimal> ULRESVDCAPACITY { get; set; }
        public Nullable<decimal> MAXUSERS { get; set; }
    }
}
