//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_800_SITEADDRESS
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public decimal ADDRESSKEY { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string TOWN { get; set; }
        public string PROVINCE { get; set; }
        public string STATE { get; set; }
        public string POSTCODE { get; set; }
        public Nullable<decimal> PERSONKEY { get; set; }
        public string IDNAME { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> DIRECTKEY { get; set; }
        public Nullable<decimal> GNDHEIGHT { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> SRCHRAD { get; set; }
        public Nullable<decimal> SRCHOVERRIDEVIEW { get; set; }
        public Nullable<decimal> NOMINALID { get; set; }
        public Nullable<decimal> TARGETSTATUS { get; set; }
        public string PROPERTYCODE { get; set; }
        public Nullable<decimal> LOCKSEARCHAREA { get; set; }
        public string FLAGVALUE { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> MASTSPACE { get; set; }
        public Nullable<decimal> MTTR { get; set; }
        public Nullable<decimal> BUILDINGHEIGHT { get; set; }
        public string PANFILE { get; set; }
        public Nullable<decimal> ASSOCMAST { get; set; }
        public Nullable<decimal> MOUNTING { get; set; }
        public Nullable<decimal> MAXHEIGHT { get; set; }
        public Nullable<decimal> MINHEIGHT { get; set; }
        public string MASTEXCLUDED { get; set; }
        public Nullable<decimal> ANTHEIGHTRULE { get; set; }
        public Nullable<decimal> ANTSTEPSIZE { get; set; }
        public string ANTHEIGHTLIST { get; set; }
        public Nullable<decimal> ANTCOLOCATION { get; set; }
        public Nullable<decimal> MINAZIMDIFF { get; set; }
        public Nullable<decimal> ANTSAMECELL { get; set; }
        public Nullable<decimal> OPTIMISATIONSTATUS { get; set; }
        public Nullable<decimal> GRIDCONSTRFLAGS { get; set; }
        public string PRECANDIDATENAME { get; set; }
    }
}
