//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_620_BSC
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public decimal SITEKEY { get; set; }
        public string IDNAME { get; set; }
        public string SITENAME { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> GNDHEIGHT { get; set; }
        public string PHOTOFILE { get; set; }
        public Nullable<decimal> MSCKEY { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public string FLAGVALUE { get; set; }
        public decimal ADDRESSKEY { get; set; }
        public string SITENAME2 { get; set; }
        public Nullable<decimal> SRCHRAD { get; set; }
        public Nullable<decimal> DIRECTKEY { get; set; }
        public string SMLCID { get; set; }
        public Nullable<decimal> BSCNETWORKID { get; set; }
    }
}
