//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_800_COORDSYS
    {
        public decimal PROJECTNO { get; set; }
        public string MAPGROUPKEY { get; set; }
        public string MAPCOORDSYSKEY { get; set; }
        public string MAPDATUMKEY { get; set; }
        public string MAPUNITKEY { get; set; }
        public string VISGROUPKEY { get; set; }
        public string VISCOORDSYSKEY { get; set; }
        public string VISDATUMKEY { get; set; }
        public string VISUNITKEY { get; set; }
        public Nullable<decimal> GEOSRID { get; set; }
        public Nullable<decimal> SRID { get; set; }
    }
}
