//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_90_LOGLTECELLCAR
    {
        public decimal PROJECTNO { get; set; }
        public decimal CELLCARRIERPK { get; set; }
        public decimal LTECELLFK { get; set; }
        public decimal CARRIERFK { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> MAXTXPOWER { get; set; }
        public Nullable<decimal> TRAFFICOFFSET { get; set; }
        public Nullable<decimal> CONTROLOFFSET { get; set; }
        public Nullable<decimal> SYNCOFFSET { get; set; }
        public Nullable<decimal> BROADCASTOFFSET { get; set; }
        public Nullable<decimal> MULTICASTOFFSET { get; set; }
        public Nullable<decimal> NOISEFIGURE { get; set; }
        public Nullable<byte> TXPOWERFIXED { get; set; }
        public Nullable<byte> REFSIGNALSNRTHRESHENABLED { get; set; }
        public Nullable<byte> TIMINGADVANCEENABLED { get; set; }
        public Nullable<byte> ADAPTIVEMIMOTHRESHENABLED { get; set; }
        public Nullable<byte> MUMIMOTHRESHENABLED { get; set; }
        public Nullable<decimal> TIMINGADVANCEMODE { get; set; }
        public Nullable<decimal> MAXTA { get; set; }
        public Nullable<decimal> MAXRANGE { get; set; }
        public Nullable<decimal> REFSIGNALSNRTHRESH { get; set; }
        public Nullable<decimal> ADAPTIVEMIMOTHRESH { get; set; }
        public Nullable<decimal> MUMIMOTHRESH { get; set; }
        public Nullable<decimal> SCHEDULERKEY { get; set; }
        public Nullable<decimal> MAXSCHEDULEDUSERS { get; set; }
        public Nullable<decimal> CODESCHEMAKEY { get; set; }
        public Nullable<decimal> CODESCHEMATYPE { get; set; }
        public decimal CELLID { get; set; }
        public Nullable<byte> CELLSPECIFICFREQOFFSETS { get; set; }
        public Nullable<decimal> MODULATIONKEY { get; set; }
        public Nullable<decimal> DLCELLCENTERLOAD { get; set; }
        public Nullable<decimal> DLCELLEDGELOAD { get; set; }
        public Nullable<decimal> MEANULCELLCENTERINTFLEVEL { get; set; }
        public Nullable<decimal> MEANULCELLEDGEINTFLEVEL { get; set; }
        public Nullable<byte> ICICSCHEMESENABLED { get; set; }
        public Nullable<decimal> RSRP { get; set; }
        public Nullable<decimal> RELRSRP { get; set; }
        public Nullable<byte> CELLEDGETHRESHMODE { get; set; }
        public Nullable<byte> CALCULATIONMETHOD { get; set; }
        public Nullable<decimal> REFERENCESIGNALPPRE { get; set; }
        public Nullable<byte> HIGHSINRLOCATIONENABLED { get; set; }
        public Nullable<byte> LINEOFSIGHTLOCATIONENABLED { get; set; }
        public Nullable<decimal> NONERAYLEIGHADJUSTMENT { get; set; }
        public Nullable<decimal> SINRTHRESHOLD { get; set; }
    }
}
