//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_800_CELLAY
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public decimal CELLAYKEY { get; set; }
        public string IDNAME { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> NETWORK { get; set; }
        public Nullable<decimal> IWEIGHT { get; set; }
        public Nullable<decimal> CCMAP { get; set; }
        public Nullable<decimal> SUPERLAYER { get; set; }
        public Nullable<decimal> CAOFFSET { get; set; }
        public Nullable<decimal> MEANCI { get; set; }
    }
}
