//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_620_FLAGVALUES
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public decimal FLAGGROUPKEY { get; set; }
        public decimal FLAGKEY { get; set; }
        public decimal ELEMENTTYPEKEY { get; set; }
        public decimal OBJECTKEY { get; set; }
        public Nullable<decimal> INTFIELDDATA { get; set; }
        public Nullable<decimal> FLOATFIELDDATA { get; set; }
        public string STRINGFIELDDATA { get; set; }
        public decimal MODIFYUSER { get; set; }
    }
}
