//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_90_LOGWIMAXMOBANTENNA
    {
        public decimal NODEANTENNAPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal LOGNODEFK { get; set; }
        public decimal ANTTYPEFK { get; set; }
        public Nullable<decimal> INDEXNO { get; set; }
        public Nullable<decimal> CORRFACTOR { get; set; }
        public Nullable<decimal> REPEATER { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> ANTTYPEFIXED { get; set; }
        public Nullable<decimal> MAXLOBETILT { get; set; }
        public decimal ULGAINCORRFACTOR { get; set; }
        public Nullable<decimal> PREDMODELKEY1 { get; set; }
        public Nullable<decimal> PREDRADIUSMET1 { get; set; }
        public Nullable<decimal> PREDRADIUSIMP1 { get; set; }
        public Nullable<decimal> PREDRESOLUTIONMET1 { get; set; }
        public Nullable<decimal> PREDRESOLUTIONIMP1 { get; set; }
        public Nullable<decimal> PREDMODELKEY2 { get; set; }
        public Nullable<decimal> PREDRADIUSMET2 { get; set; }
        public Nullable<decimal> PREDRADIUSIMP2 { get; set; }
        public Nullable<decimal> PREDRESOLUTIONMET2 { get; set; }
        public Nullable<decimal> PREDRESOLUTIONIMP2 { get; set; }
        public string INSTANCEID { get; set; }
        public Nullable<decimal> ELECTILTSTEP { get; set; }
        public Nullable<decimal> MAXELECTILT { get; set; }
        public Nullable<decimal> MINELECTILT { get; set; }
        public Nullable<decimal> MINLOBETILT { get; set; }
        public decimal PHYANTENNAFK { get; set; }
        public string PORTS { get; set; }
        public decimal SITEADDRESSKEY { get; set; }
        public Nullable<decimal> ETILT { get; set; }
        public Nullable<decimal> FREQBAND { get; set; }
        public Nullable<decimal> INHERITMASTERPATTERN { get; set; }
        public string DIPLEXERS { get; set; }
    }
}
