//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_91_PMPHUBLINKEND
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public decimal PMPHUBLINKENDKEY { get; set; }
        public Nullable<decimal> PMPCARRIERKEY { get; set; }
        public Nullable<decimal> PMPSECTORKEY { get; set; }
        public decimal PMPHUBKEY { get; set; }
        public decimal LINKKEY { get; set; }
        public Nullable<decimal> LINKTERMEQUIPKEY { get; set; }
        public Nullable<decimal> AVGREFRACTIVITY { get; set; }
        public Nullable<decimal> MINANTHEIGHT { get; set; }
        public Nullable<decimal> INCLINATION { get; set; }
        public Nullable<decimal> BEARING { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> ANNUALAVAIL { get; set; }
        public Nullable<decimal> DIVCMPFADEMARGIN { get; set; }
        public Nullable<decimal> CMPFADEMARGIN { get; set; }
        public Nullable<decimal> ANNUALRELIAB { get; set; }
        public Nullable<decimal> RXLEVEL { get; set; }
        public Nullable<decimal> DIVRXLEVEL { get; set; }
    }
}
