//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_620_LOGIS95BS
    {
        public decimal LOGNODEPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> SECTORRADIUS { get; set; }
        public Nullable<decimal> PREDRADIUS { get; set; }
        public Nullable<decimal> PREDRESOLUTION { get; set; }
        public Nullable<decimal> NUMCHANSPOOL { get; set; }
        public Nullable<decimal> MAXHOCHANSPOOL { get; set; }
        public Nullable<decimal> MAXPRIMCHANSPOOL { get; set; }
        public Nullable<decimal> LOGNODETYPEFK { get; set; }
    }
}
