//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_620_REPEATER
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public decimal SITEKEY { get; set; }
        public string IDNAME { get; set; }
        public string SITENAME { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> GNDHEIGHT { get; set; }
        public string PHOTOFILE { get; set; }
        public Nullable<decimal> HEXRADIUS { get; set; }
        public Nullable<decimal> CABINKEY { get; set; }
        public Nullable<decimal> BTSKEY { get; set; }
        public Nullable<decimal> TOWERKEY { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public string FLAGVALUE { get; set; }
        public Nullable<decimal> PREDRADIUS { get; set; }
        public Nullable<decimal> PREDRESOLUTION { get; set; }
        public Nullable<decimal> RXANTENNAKEY { get; set; }
        public Nullable<decimal> AZIMUTH { get; set; }
        public Nullable<decimal> TILT { get; set; }
        public Nullable<decimal> RXSIGNAL { get; set; }
        public Nullable<decimal> OUTPUTPOWER { get; set; }
        public Nullable<decimal> CALCMETHOD { get; set; }
        public Nullable<decimal> POWER0 { get; set; }
        public Nullable<decimal> POWER1 { get; set; }
        public Nullable<decimal> POWER2 { get; set; }
        public Nullable<decimal> POWER3 { get; set; }
        public Nullable<decimal> POWER4 { get; set; }
        public Nullable<decimal> POWER5 { get; set; }
        public Nullable<decimal> POWER6 { get; set; }
        public Nullable<decimal> POWER7 { get; set; }
        public Nullable<decimal> POWER8 { get; set; }
        public Nullable<decimal> POWER9 { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> GAIN { get; set; }
        public Nullable<decimal> RXTHRESHOLD { get; set; }
        public Nullable<decimal> CELLKEY { get; set; }
        public decimal ADDRESSKEY { get; set; }
        public string SITENAME2 { get; set; }
        public Nullable<decimal> SRCHRAD { get; set; }
        public Nullable<decimal> SRCHPERC { get; set; }
        public Nullable<decimal> USEPERC { get; set; }
        public Nullable<decimal> BTSFIXED { get; set; }
    }
}
