//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_800_CARLAY
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public decimal CARLAYKEY { get; set; }
        public string IDNAME { get; set; }
        public string ABBREVIATION { get; set; }
        public Nullable<decimal> MAXCARRIERS { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> USEREUSEPATTERN { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> COLOURCODE { get; set; }
        public Nullable<decimal> FREQBANDKEY { get; set; }
    }
}
