//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_800_PRIORUSERRIGHTS
    {
        public decimal OPTIONIDPK { get; set; }
        public decimal USRTYPEFK { get; set; }
        public decimal PARENTOPTIONID { get; set; }
        public decimal ISSECTIONHEADERONLY { get; set; }
        public decimal ALLOWED { get; set; }
        public decimal ALLOWEDBYDEFAULT { get; set; }
        public string ENGLISHNAME { get; set; }
        public string IDNAME { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
