//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_90_LOGWIMAXCELLCAR
    {
        public decimal PROJECTNO { get; set; }
        public decimal CELLCARRIERPK { get; set; }
        public decimal WIMAXCELLFK { get; set; }
        public decimal CARRIERFK { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CELLBGRNDNOISE { get; set; }
        public Nullable<decimal> NOISERISE { get; set; }
        public Nullable<byte> WIMAXTXPOWFIXED { get; set; }
        public decimal RXSENS { get; set; }
        public decimal CONTROLPWR { get; set; }
        public decimal CONTROLACT { get; set; }
        public decimal SUBCHANNEL { get; set; }
        public decimal WIMAXTXPWR { get; set; }
        public decimal WIMAXDLTRAFFPWRDBM { get; set; }
    }
}
