//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_91_LOGWIMAXNODE
    {
        public Nullable<decimal> LOGNODEPK { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
        public Nullable<decimal> PROJECTNO { get; set; }
        public Nullable<decimal> MODIFYUSER { get; set; }
        public Nullable<decimal> CELLRADIUS { get; set; }
        public Nullable<decimal> PREDRADIUS { get; set; }
        public Nullable<decimal> PREDRESOLUTION { get; set; }
        public Nullable<decimal> NODEID { get; set; }
        public Nullable<decimal> CAPACITY { get; set; }
    }
}
