//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_91_ACTIVEATTRIB
    {
        public Nullable<decimal> PROJECTNO { get; set; }
        public decimal FILTERKEY { get; set; }
        public decimal RULEKEY { get; set; }
        public decimal ACTIVEATTRIBUTEKEY { get; set; }
        public decimal ATTRIBUTENUM { get; set; }
        public Nullable<decimal> PICKEDOBJECTKEY { get; set; }
        public Nullable<decimal> ELEMENTTYPEKEY { get; set; }
        public Nullable<decimal> BOOL { get; set; }
        public Nullable<decimal> NUMBERA { get; set; }
        public Nullable<decimal> NUMBERB { get; set; }
        public string STRING { get; set; }
        public string CELLLAYERID { get; set; }
        public string CARLAYERID { get; set; }
        public Nullable<decimal> OBJECTKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
    }
}
