//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_91_LOGCELL
    {
        public decimal LOGCELLPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public decimal LOGCELLTYPEFK { get; set; }
        public decimal LOGNODEFK { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
        public string IDNAME { get; set; }
        public string SECNAME { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> VISIBILITY { get; set; }
        public Nullable<decimal> VISIBILITYGROUP { get; set; }
        public Nullable<decimal> CELLOVERRIDECOLORREF { get; set; }
        public decimal CSAREA { get; set; }
        public decimal CSRANGE { get; set; }
    }
}
