//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_91_LOGIS95SECTOR
    {
        public decimal LOGCELLPK { get; set; }
        public decimal PROJECTNO { get; set; }
        public Nullable<decimal> PNCODE { get; set; }
        public Nullable<decimal> NUMCHANSPOOL { get; set; }
        public Nullable<decimal> MAXHOCHANSPOOL { get; set; }
        public Nullable<decimal> MAXPRIMCHANSPOOL { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> SIGNALLINGOVERHEAD { get; set; }
        public decimal LOGCELLTYPEFK { get; set; }
    }
}
