//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_800_CELLSITES
    {
        public decimal PROJECTNO { get; set; }
        public decimal LOGNODEPK { get; set; }
        public Nullable<decimal> GNDHEIGHT { get; set; }
        public string PHOTOFILE { get; set; }
        public Nullable<decimal> HEXRADIUS { get; set; }
        public Nullable<decimal> BSCKEY { get; set; }
        public Nullable<decimal> CABINKEY { get; set; }
        public Nullable<decimal> BTSKEY { get; set; }
        public Nullable<decimal> TOWERKEY { get; set; }
        public decimal MODIFYUSER { get; set; }
        public string FLAGVALUE { get; set; }
        public Nullable<decimal> PREDRADIUS { get; set; }
        public Nullable<decimal> PREDRESOLUTION { get; set; }
        public Nullable<decimal> MSCKEY { get; set; }
        public Nullable<decimal> SRCHRAD { get; set; }
        public Nullable<decimal> SRCHPERC { get; set; }
        public Nullable<decimal> USEPERC { get; set; }
        public Nullable<decimal> GSMTSPC { get; set; }
        public Nullable<decimal> AMPTSPC { get; set; }
        public Nullable<decimal> GSMEXTS { get; set; }
        public Nullable<decimal> AMPEXTS { get; set; }
        public Nullable<decimal> GSMBITRATE { get; set; }
        public Nullable<decimal> AMPBITRATE { get; set; }
        public Nullable<decimal> DIRECTKEY { get; set; }
        public Nullable<decimal> BTSFIXED { get; set; }
        public Nullable<decimal> LAC { get; set; }
        public Nullable<decimal> HASCONSTRAINTS { get; set; }
        public Nullable<decimal> MINSECTORS { get; set; }
        public Nullable<decimal> MAXSECTORS { get; set; }
        public Nullable<decimal> GRDCSTRNTFLAGS { get; set; }
        public decimal LOGNODETYPEFK { get; set; }
        public Nullable<decimal> NETWORKLEVEL { get; set; }
        public Nullable<decimal> CAPACITY { get; set; }
    }
}
