//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPG_620_PRIORUSERRM
    {
        public decimal USRKEY { get; set; }
        public string USR { get; set; }
        public string USRCOM { get; set; }
        public Nullable<decimal> PROJECTPRIV { get; set; }
        public Nullable<decimal> DEFAULTGRP { get; set; }
        public Nullable<decimal> SITEMASK { get; set; }
        public Nullable<decimal> USRTYPE { get; set; }
        public Nullable<decimal> EXTAUTH { get; set; }
        public Nullable<decimal> PN { get; set; }
    }
}
