//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VECATTR
    {
        public decimal VECID { get; set; }
        public decimal SEGID { get; set; }
        public decimal ATTRID { get; set; }
        public Nullable<decimal> DATATYPE { get; set; }
        public string DATANAME { get; set; }
        public Nullable<decimal> FLOATVALUE { get; set; }
        public Nullable<decimal> INTVALUE { get; set; }
        public string STRINGVALUE { get; set; }
        public Nullable<decimal> STRINGANGLE { get; set; }
        public Nullable<decimal> FILEID { get; set; }
    }
}
