//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSMAPPINGS
    {
        public decimal PROJECTNO { get; set; }
        public decimal WFSMAPPINGPK { get; set; }
        public decimal WFSSERVICEFK { get; set; }
        public decimal OBJECTTYPEFK { get; set; }
        public string WFSFEATURE { get; set; }
        public string WFSATTRIB { get; set; }
        public decimal ENABLED { get; set; }
        public decimal CREATEUSER { get; set; }
        public decimal MODIFYUSER { get; set; }
        public decimal USERGROUP { get; set; }
        public decimal PERMISSION { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public System.DateTime MODIFYDATE { get; set; }
    }
}
