//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIMAXMOBCARRIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WIMAXMOBCARRIER()
        {
            this.LOGWIMAXMOBCAR = new HashSet<LOGWIMAXMOBCAR>();
            this.WIMAXMOBCARRIERADJ = new HashSet<WIMAXMOBCARRIERADJ>();
        }
    
        public decimal PROJECTNO { get; set; }
        public decimal CARRIERNO { get; set; }
        public decimal MODIFYUSER { get; set; }
        public Nullable<decimal> PERMISSION { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> USERGROUP { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public decimal FREQUENCY { get; set; }
        public decimal BANDWIDTH { get; set; }
        public Nullable<decimal> FRAMEDURATION { get; set; }
        public Nullable<decimal> TRANSITIONGAP { get; set; }
        public Nullable<decimal> CYCLICPREFIX { get; set; }
        public Nullable<decimal> DUPLEX { get; set; }
        public Nullable<decimal> DLFUSC { get; set; }
        public Nullable<decimal> DLPUSC { get; set; }
        public Nullable<decimal> FIXMAPDL { get; set; }
        public Nullable<decimal> FIXMAPUL { get; set; }
        public Nullable<decimal> DLAMC { get; set; }
        public Nullable<decimal> ULAMC { get; set; }
        public Nullable<decimal> DLOPUSC { get; set; }
        public Nullable<decimal> ULOPUSC { get; set; }
        public Nullable<decimal> ULPUSC { get; set; }
        public string IDNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGWIMAXMOBCAR> LOGWIMAXMOBCAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIMAXMOBCARRIERADJ> WIMAXMOBCARRIERADJ { get; set; }
    }
}
